// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/modules/analytics/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockIMetricRepository is an autogenerated mock type for the IMetricRepository type
type MockIMetricRepository struct {
	mock.Mock
}

type MockIMetricRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMetricRepository) EXPECT() *MockIMetricRepository_Expecter {
	return &MockIMetricRepository_Expecter{mock: &_m.Mock}
}

// DeleteOlderThan provides a mock function with given fields: ctx, days
func (_m *MockIMetricRepository) DeleteOlderThan(ctx context.Context, days int) (int64, error) {
	ret := _m.Called(ctx, days)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, days)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, days)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, days)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMetricRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockIMetricRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - days int
func (_e *MockIMetricRepository_Expecter) DeleteOlderThan(ctx interface{}, days interface{}) *MockIMetricRepository_DeleteOlderThan_Call {
	return &MockIMetricRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, days)}
}

func (_c *MockIMetricRepository_DeleteOlderThan_Call) Run(run func(ctx context.Context, days int)) *MockIMetricRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIMetricRepository_DeleteOlderThan_Call) Return(_a0 int64, _a1 error) *MockIMetricRepository_DeleteOlderThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMetricRepository_DeleteOlderThan_Call) RunAndReturn(run func(context.Context, int) (int64, error)) *MockIMetricRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIMetricRepository) GetByID(ctx context.Context, id string) (*entity.Metric, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Metric, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Metric); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMetricRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIMetricRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIMetricRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIMetricRepository_GetByID_Call {
	return &MockIMetricRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIMetricRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockIMetricRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIMetricRepository_GetByID_Call) Return(_a0 *entity.Metric, _a1 error) *MockIMetricRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMetricRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*entity.Metric, error)) *MockIMetricRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestByName provides a mock function with given fields: ctx, module, scope, scopeID, name
func (_m *MockIMetricRepository) GetLatestByName(ctx context.Context, module string, scope string, scopeID string, name string) (*entity.Metric, error) {
	ret := _m.Called(ctx, module, scope, scopeID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByName")
	}

	var r0 *entity.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*entity.Metric, error)); ok {
		return rf(ctx, module, scope, scopeID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *entity.Metric); ok {
		r0 = rf(ctx, module, scope, scopeID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, module, scope, scopeID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIMetricRepository_GetLatestByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestByName'
type MockIMetricRepository_GetLatestByName_Call struct {
	*mock.Call
}

// GetLatestByName is a helper method to define mock.On call
//   - ctx context.Context
//   - module string
//   - scope string
//   - scopeID string
//   - name string
func (_e *MockIMetricRepository_Expecter) GetLatestByName(ctx interface{}, module interface{}, scope interface{}, scopeID interface{}, name interface{}) *MockIMetricRepository_GetLatestByName_Call {
	return &MockIMetricRepository_GetLatestByName_Call{Call: _e.mock.On("GetLatestByName", ctx, module, scope, scopeID, name)}
}

func (_c *MockIMetricRepository_GetLatestByName_Call) Run(run func(ctx context.Context, module string, scope string, scopeID string, name string)) *MockIMetricRepository_GetLatestByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockIMetricRepository_GetLatestByName_Call) Return(_a0 *entity.Metric, _a1 error) *MockIMetricRepository_GetLatestByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIMetricRepository_GetLatestByName_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*entity.Metric, error)) *MockIMetricRepository_GetLatestByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListByModule provides a mock function with given fields: ctx, module, limit, offset
func (_m *MockIMetricRepository) ListByModule(ctx context.Context, module string, limit int, offset int) ([]*entity.Metric, int64, error) {
	ret := _m.Called(ctx, module, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByModule")
	}

	var r0 []*entity.Metric
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.Metric, int64, error)); ok {
		return rf(ctx, module, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.Metric); ok {
		r0 = rf(ctx, module, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, module, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, module, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIMetricRepository_ListByModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByModule'
type MockIMetricRepository_ListByModule_Call struct {
	*mock.Call
}

// ListByModule is a helper method to define mock.On call
//   - ctx context.Context
//   - module string
//   - limit int
//   - offset int
func (_e *MockIMetricRepository_Expecter) ListByModule(ctx interface{}, module interface{}, limit interface{}, offset interface{}) *MockIMetricRepository_ListByModule_Call {
	return &MockIMetricRepository_ListByModule_Call{Call: _e.mock.On("ListByModule", ctx, module, limit, offset)}
}

func (_c *MockIMetricRepository_ListByModule_Call) Run(run func(ctx context.Context, module string, limit int, offset int)) *MockIMetricRepository_ListByModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIMetricRepository_ListByModule_Call) Return(_a0 []*entity.Metric, _a1 int64, _a2 error) *MockIMetricRepository_ListByModule_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIMetricRepository_ListByModule_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*entity.Metric, int64, error)) *MockIMetricRepository_ListByModule_Call {
	_c.Call.Return(run)
	return _c
}

// ListByScope provides a mock function with given fields: ctx, scope, scopeID, limit, offset
func (_m *MockIMetricRepository) ListByScope(ctx context.Context, scope string, scopeID string, limit int, offset int) ([]*entity.Metric, int64, error) {
	ret := _m.Called(ctx, scope, scopeID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByScope")
	}

	var r0 []*entity.Metric
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*entity.Metric, int64, error)); ok {
		return rf(ctx, scope, scopeID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*entity.Metric); ok {
		r0 = rf(ctx, scope, scopeID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) int64); ok {
		r1 = rf(ctx, scope, scopeID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int) error); ok {
		r2 = rf(ctx, scope, scopeID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIMetricRepository_ListByScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByScope'
type MockIMetricRepository_ListByScope_Call struct {
	*mock.Call
}

// ListByScope is a helper method to define mock.On call
//   - ctx context.Context
//   - scope string
//   - scopeID string
//   - limit int
//   - offset int
func (_e *MockIMetricRepository_Expecter) ListByScope(ctx interface{}, scope interface{}, scopeID interface{}, limit interface{}, offset interface{}) *MockIMetricRepository_ListByScope_Call {
	return &MockIMetricRepository_ListByScope_Call{Call: _e.mock.On("ListByScope", ctx, scope, scopeID, limit, offset)}
}

func (_c *MockIMetricRepository_ListByScope_Call) Run(run func(ctx context.Context, scope string, scopeID string, limit int, offset int)) *MockIMetricRepository_ListByScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockIMetricRepository_ListByScope_Call) Return(_a0 []*entity.Metric, _a1 int64, _a2 error) *MockIMetricRepository_ListByScope_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIMetricRepository_ListByScope_Call) RunAndReturn(run func(context.Context, string, string, int, int) ([]*entity.Metric, int64, error)) *MockIMetricRepository_ListByScope_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, metric
func (_m *MockIMetricRepository) Store(ctx context.Context, metric *entity.Metric) error {
	ret := _m.Called(ctx, metric)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Metric) error); ok {
		r0 = rf(ctx, metric)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIMetricRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockIMetricRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - metric *entity.Metric
func (_e *MockIMetricRepository_Expecter) Store(ctx interface{}, metric interface{}) *MockIMetricRepository_Store_Call {
	return &MockIMetricRepository_Store_Call{Call: _e.mock.On("Store", ctx, metric)}
}

func (_c *MockIMetricRepository_Store_Call) Run(run func(ctx context.Context, metric *entity.Metric)) *MockIMetricRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Metric))
	})
	return _c
}

func (_c *MockIMetricRepository_Store_Call) Return(_a0 error) *MockIMetricRepository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIMetricRepository_Store_Call) RunAndReturn(run func(context.Context, *entity.Metric) error) *MockIMetricRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIMetricRepository creates a new instance of MockIMetricRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMetricRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMetricRepository {
	mock := &MockIMetricRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
