// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/modules/analytics/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockMetricRepository is an autogenerated mock type for the IMetricRepository type
type MockMetricRepository struct {
	mock.Mock
}

// DeleteOlderThan provides a mock function with given fields: ctx, days
func (_m *MockMetricRepository) DeleteOlderThan(ctx context.Context, days int) (int64, error) {
	ret := _m.Called(ctx, days)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return rf(ctx, days)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = rf(ctx, days)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, days)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockMetricRepository) GetByID(ctx context.Context, id string) (*entity.Metric, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Metric, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Metric); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestByName provides a mock function with given fields: ctx, module, scope, scopeID, name
func (_m *MockMetricRepository) GetLatestByName(ctx context.Context, module string, scope string, scopeID string, name string) (*entity.Metric, error) {
	ret := _m.Called(ctx, module, scope, scopeID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestByName")
	}

	var r0 *entity.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*entity.Metric, error)); ok {
		return rf(ctx, module, scope, scopeID, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *entity.Metric); ok {
		r0 = rf(ctx, module, scope, scopeID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, module, scope, scopeID, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByModule provides a mock function with given fields: ctx, module, limit, offset
func (_m *MockMetricRepository) ListByModule(ctx context.Context, module string, limit int, offset int) ([]*entity.Metric, int64, error) {
	ret := _m.Called(ctx, module, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByModule")
	}

	var r0 []*entity.Metric
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.Metric, int64, error)); ok {
		return rf(ctx, module, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.Metric); ok {
		r0 = rf(ctx, module, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, module, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, module, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListByScope provides a mock function with given fields: ctx, scope, scopeID, limit, offset
func (_m *MockMetricRepository) ListByScope(ctx context.Context, scope string, scopeID string, limit int, offset int) ([]*entity.Metric, int64, error) {
	ret := _m.Called(ctx, scope, scopeID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByScope")
	}

	var r0 []*entity.Metric
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*entity.Metric, int64, error)); ok {
		return rf(ctx, scope, scopeID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*entity.Metric); ok {
		r0 = rf(ctx, scope, scopeID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) int64); ok {
		r1 = rf(ctx, scope, scopeID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int) error); ok {
		r2 = rf(ctx, scope, scopeID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store provides a mock function with given fields: ctx, metric
func (_m *MockMetricRepository) Store(ctx context.Context, metric *entity.Metric) error {
	ret := _m.Called(ctx, metric)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Metric) error); ok {
		r0 = rf(ctx, metric)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMetricRepository creates a new instance of MockMetricRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricRepository {
	mock := &MockMetricRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
