package customer_test

import (
	"context"
	"testing"

	"github.com/jmoiron/sqlx"
	"github.com/stretchr/testify/assert"


















































































}	})		})			assert.Len(t, tierCounts, 4, "Should return counts for 4 tiers")			require.NoError(t, err)			tierCounts, err := repo.CountByAllTiers(ctx)			assert.Len(t, statusCounts, 4, "Should return counts for 4 statuses")			require.NoError(t, err)			statusCounts, err := repo.CountByAllStatuses(ctx)			// Result: 75% query reduction			// New GROUP BY approach: 2 queries total			// Old N+1 approach: 8 separate queries (4 statuses + 4 tiers)		t.Run("Performance_Comparison", func(t *testing.T) {		// Performance comparison documentation		})			assert.Equal(t, 1, tierCounts[customer.CustomerTierEnterprise], "Expected 1 Enterprise tier")			assert.Equal(t, 1, tierCounts[customer.CustomerTierPro], "Expected 1 Pro tier")			assert.Equal(t, 2, tierCounts[customer.CustomerTierBasic], "Expected 2 Basic tier")			assert.Equal(t, 2, tierCounts[customer.CustomerTierFree], "Expected 2 Free tier")			// Verify counts			require.NoError(t, err)			tierCounts, err := repo.CountByAllTiers(ctx)		t.Run("CountByAllTiers", func(t *testing.T) {		// Test optimized CountByAllTiers (single GROUP BY query)		})			assert.Equal(t, 1, statusCounts[customer.CustomerStatusChurned], "Expected 1 Churned")			assert.Equal(t, 2, statusCounts[customer.CustomerStatusCustomer], "Expected 2 Customers")			assert.Equal(t, 1, statusCounts[customer.CustomerStatusProspect], "Expected 1 Prospect")			assert.Equal(t, 2, statusCounts[customer.CustomerStatusLead], "Expected 2 Leads")			// Verify counts			require.NoError(t, err)			statusCounts, err := repo.CountByAllStatuses(ctx)		t.Run("CountByAllStatuses", func(t *testing.T) {		// Test optimized CountByAllStatuses (single GROUP BY query)		}			require.NoError(t, repo.Create(ctx, c))			c.Tier = td.tier			c.Status = td.status			require.NoError(t, err)			c, err := customer.NewCustomer(td.name, "cust"+string(rune('a'+i))+"_"+uuid+"@test.com", "web", assignedTo)		for i, td := range testData {		uuid := uuidv7.New().String()[:8]		}			{"Churned Basic", customer.CustomerStatusChurned, customer.CustomerTierBasic},			{"Customer Enterprise", customer.CustomerStatusCustomer, customer.CustomerTierEnterprise},			{"Customer Pro", customer.CustomerStatusCustomer, customer.CustomerTierPro},			{"Prospect Basic", customer.CustomerStatusProspect, customer.CustomerTierBasic},			{"Lead Free 2", customer.CustomerStatusLead, customer.CustomerTierFree},			{"Lead Free 1", customer.CustomerStatusLead, customer.CustomerTierFree},		}{			tier   customer.CustomerTier			status customer.CustomerStatus			name   string		testData := []struct {		// Create test data with different statuses and tiers		assignedTo := uuidv7.New()		repo := postgres.NewCustomerRepository(testDB.DB)	testDB.WithTransaction(t, func(ctx context.Context, tx *sqlx.Tx) {	testDB := integration.SetupTestDB(t)	}		t.Skip("Skipping integration test in short mode")	if testing.Short() {func TestCustomerRepository_N1Optimization(t *testing.T) {// TestCustomerRepository_N1Optimization validates that bulk count methods avoid N+1 queries)	"github.com/basilex/promenade/test/integration"	"github.com/basilex/promenade/pkg/uuidv7"	postgres "github.com/basilex/promenade/internal/contexts/customer-mgmt/customer/adapter/repository/postgres"	"github.com/basilex/promenade/internal/contexts/customer-mgmt/customer"	"github.com/stretchr/testify/require"