// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCityRepository is an autogenerated mock type for the CityRepository type
type MockCityRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, city
func (_m *MockCityRepository) Create(ctx context.Context, city *entity.City) error {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.City) error); ok {
		r0 = rf(ctx, city)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCityRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCityRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.City, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.City, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.City); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *MockCityRepository) List(ctx context.Context, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.City); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListActive provides a mock function with given fields: ctx, offset, limit
func (_m *MockCityRepository) ListActive(ctx context.Context, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.City); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListActiveByCountry provides a mock function with given fields: ctx, countryID, offset, limit
func (_m *MockCityRepository) ListActiveByCountry(ctx context.Context, countryID uuid.UUID, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, countryID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByCountry")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, countryID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.City); ok {
		r0 = rf(ctx, countryID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, countryID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, countryID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListByCountry provides a mock function with given fields: ctx, countryID, offset, limit
func (_m *MockCityRepository) ListByCountry(ctx context.Context, countryID uuid.UUID, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, countryID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByCountry")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, countryID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.City); ok {
		r0 = rf(ctx, countryID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, countryID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, countryID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListByRegion provides a mock function with given fields: ctx, regionID, offset, limit
func (_m *MockCityRepository) ListByRegion(ctx context.Context, regionID uuid.UUID, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, regionID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByRegion")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, regionID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.City); ok {
		r0 = rf(ctx, regionID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, regionID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, regionID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListCapitals provides a mock function with given fields: ctx, offset, limit
func (_m *MockCityRepository) ListCapitals(ctx context.Context, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCapitals")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.City); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SearchByName provides a mock function with given fields: ctx, query, offset, limit
func (_m *MockCityRepository) SearchByName(ctx context.Context, query string, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, query, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, query, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []entity.City); ok {
		r0 = rf(ctx, query, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, query, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, query, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, city
func (_m *MockCityRepository) Update(ctx context.Context, city *entity.City) error {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.City) error); ok {
		r0 = rf(ctx, city)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCityRepository creates a new instance of MockCityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCityRepository {
	mock := &MockCityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
