// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCountryRepository is an autogenerated mock type for the ICountryRepository type
type MockCountryRepository struct {
	mock.Mock
}

// AddCurrency provides a mock function with given fields: ctx, countryID, currencyID, isPrimary
func (_m *MockCountryRepository) AddCurrency(ctx context.Context, countryID uuid.UUID, currencyID uuid.UUID, isPrimary bool) error {
	ret := _m.Called(ctx, countryID, currencyID, isPrimary)

	if len(ret) == 0 {
		panic("no return value specified for AddCurrency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, countryID, currencyID, isPrimary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, country
func (_m *MockCountryRepository) Create(ctx context.Context, country *entity.Country) error {
	ret := _m.Called(ctx, country)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Country) error); ok {
		r0 = rf(ctx, country)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCountryRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCode provides a mock function with given fields: ctx, code, withCurrencies
func (_m *MockCountryRepository) GetByCode(ctx context.Context, code string, withCurrencies bool) (*entity.Country, error) {
	ret := _m.Called(ctx, code, withCurrencies)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*entity.Country, error)); ok {
		return rf(ctx, code, withCurrencies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *entity.Country); ok {
		r0 = rf(ctx, code, withCurrencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, code, withCurrencies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id, withCurrencies
func (_m *MockCountryRepository) GetByID(ctx context.Context, id uuid.UUID, withCurrencies bool) (*entity.Country, error) {
	ret := _m.Called(ctx, id, withCurrencies)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*entity.Country, error)); ok {
		return rf(ctx, id, withCurrencies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *entity.Country); ok {
		r0 = rf(ctx, id, withCurrencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, id, withCurrencies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrencies provides a mock function with given fields: ctx, countryID
func (_m *MockCountryRepository) GetCurrencies(ctx context.Context, countryID uuid.UUID) ([]entity.Currency, error) {
	ret := _m.Called(ctx, countryID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencies")
	}

	var r0 []entity.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Currency, error)); ok {
		return rf(ctx, countryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Currency); ok {
		r0 = rf(ctx, countryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, countryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, offset, limit, withCurrencies
func (_m *MockCountryRepository) List(ctx context.Context, offset int, limit int, withCurrencies bool) ([]entity.Country, int, error) {
	ret := _m.Called(ctx, offset, limit, withCurrencies)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Country
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool) ([]entity.Country, int, error)); ok {
		return rf(ctx, offset, limit, withCurrencies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool) []entity.Country); ok {
		r0 = rf(ctx, offset, limit, withCurrencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, bool) int); ok {
		r1 = rf(ctx, offset, limit, withCurrencies)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, bool) error); ok {
		r2 = rf(ctx, offset, limit, withCurrencies)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListByRegion provides a mock function with given fields: ctx, region, offset, limit, withCurrencies
func (_m *MockCountryRepository) ListByRegion(ctx context.Context, region string, offset int, limit int, withCurrencies bool) ([]entity.Country, int, error) {
	ret := _m.Called(ctx, region, offset, limit, withCurrencies)

	if len(ret) == 0 {
		panic("no return value specified for ListByRegion")
	}

	var r0 []entity.Country
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) ([]entity.Country, int, error)); ok {
		return rf(ctx, region, offset, limit, withCurrencies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) []entity.Country); ok {
		r0 = rf(ctx, region, offset, limit, withCurrencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, bool) int); ok {
		r1 = rf(ctx, region, offset, limit, withCurrencies)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, bool) error); ok {
		r2 = rf(ctx, region, offset, limit, withCurrencies)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RemoveCurrency provides a mock function with given fields: ctx, countryID, currencyID
func (_m *MockCountryRepository) RemoveCurrency(ctx context.Context, countryID uuid.UUID, currencyID uuid.UUID) error {
	ret := _m.Called(ctx, countryID, currencyID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCurrency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, countryID, currencyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, country
func (_m *MockCountryRepository) Update(ctx context.Context, country *entity.Country) error {
	ret := _m.Called(ctx, country)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Country) error); ok {
		r0 = rf(ctx, country)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCountryRepository creates a new instance of MockCountryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCountryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCountryRepository {
	mock := &MockCountryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
