// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockCurrencyRepository is an autogenerated mock type for the CurrencyRepository type
type MockCurrencyRepository struct {
	mock.Mock
}

// AddCountry provides a mock function with given fields: ctx, currencyID, countryID, isPrimary
func (_m *MockCurrencyRepository) AddCountry(ctx context.Context, currencyID uuid.UUID, countryID uuid.UUID, isPrimary bool) error {
	ret := _m.Called(ctx, currencyID, countryID, isPrimary)

	if len(ret) == 0 {
		panic("no return value specified for AddCountry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, currencyID, countryID, isPrimary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, currency
func (_m *MockCurrencyRepository) Create(ctx context.Context, currency *entity.Currency) error {
	ret := _m.Called(ctx, currency)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Currency) error); ok {
		r0 = rf(ctx, currency)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCurrencyRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCode provides a mock function with given fields: ctx, code, withCountries
func (_m *MockCurrencyRepository) GetByCode(ctx context.Context, code string, withCountries bool) (*entity.Currency, error) {
	ret := _m.Called(ctx, code, withCountries)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*entity.Currency, error)); ok {
		return rf(ctx, code, withCountries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *entity.Currency); ok {
		r0 = rf(ctx, code, withCountries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, code, withCountries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id, withCountries
func (_m *MockCurrencyRepository) GetByID(ctx context.Context, id uuid.UUID, withCountries bool) (*entity.Currency, error) {
	ret := _m.Called(ctx, id, withCountries)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*entity.Currency, error)); ok {
		return rf(ctx, id, withCountries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *entity.Currency); ok {
		r0 = rf(ctx, id, withCountries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, id, withCountries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCountries provides a mock function with given fields: ctx, currencyID
func (_m *MockCurrencyRepository) GetCountries(ctx context.Context, currencyID uuid.UUID) ([]entity.Country, error) {
	ret := _m.Called(ctx, currencyID)

	if len(ret) == 0 {
		panic("no return value specified for GetCountries")
	}

	var r0 []entity.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Country, error)); ok {
		return rf(ctx, currencyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Country); ok {
		r0 = rf(ctx, currencyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, currencyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, offset, limit, withCountries
func (_m *MockCurrencyRepository) List(ctx context.Context, offset int, limit int, withCountries bool) ([]entity.Currency, int, error) {
	ret := _m.Called(ctx, offset, limit, withCountries)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Currency
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool) ([]entity.Currency, int, error)); ok {
		return rf(ctx, offset, limit, withCountries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool) []entity.Currency); ok {
		r0 = rf(ctx, offset, limit, withCountries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, bool) int); ok {
		r1 = rf(ctx, offset, limit, withCountries)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, bool) error); ok {
		r2 = rf(ctx, offset, limit, withCountries)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RemoveCountry provides a mock function with given fields: ctx, currencyID, countryID
func (_m *MockCurrencyRepository) RemoveCountry(ctx context.Context, currencyID uuid.UUID, countryID uuid.UUID) error {
	ret := _m.Called(ctx, currencyID, countryID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCountry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, currencyID, countryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, currency
func (_m *MockCurrencyRepository) Update(ctx context.Context, currency *entity.Currency) error {
	ret := _m.Called(ctx, currency)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Currency) error); ok {
		r0 = rf(ctx, currency)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCurrencyRepository creates a new instance of MockCurrencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCurrencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCurrencyRepository {
	mock := &MockCurrencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
