// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockICurrencyRepository is an autogenerated mock type for the ICurrencyRepository type
type MockICurrencyRepository struct {
	mock.Mock
}

type MockICurrencyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICurrencyRepository) EXPECT() *MockICurrencyRepository_Expecter {
	return &MockICurrencyRepository_Expecter{mock: &_m.Mock}
}

// AddCountry provides a mock function with given fields: ctx, currencyID, countryID, isPrimary
func (_m *MockICurrencyRepository) AddCountry(ctx context.Context, currencyID uuid.UUID, countryID uuid.UUID, isPrimary bool) error {
	ret := _m.Called(ctx, currencyID, countryID, isPrimary)

	if len(ret) == 0 {
		panic("no return value specified for AddCountry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, currencyID, countryID, isPrimary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICurrencyRepository_AddCountry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCountry'
type MockICurrencyRepository_AddCountry_Call struct {
	*mock.Call
}

// AddCountry is a helper method to define mock.On call
//   - ctx context.Context
//   - currencyID uuid.UUID
//   - countryID uuid.UUID
//   - isPrimary bool
func (_e *MockICurrencyRepository_Expecter) AddCountry(ctx interface{}, currencyID interface{}, countryID interface{}, isPrimary interface{}) *MockICurrencyRepository_AddCountry_Call {
	return &MockICurrencyRepository_AddCountry_Call{Call: _e.mock.On("AddCountry", ctx, currencyID, countryID, isPrimary)}
}

func (_c *MockICurrencyRepository_AddCountry_Call) Run(run func(ctx context.Context, currencyID uuid.UUID, countryID uuid.UUID, isPrimary bool)) *MockICurrencyRepository_AddCountry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockICurrencyRepository_AddCountry_Call) Return(_a0 error) *MockICurrencyRepository_AddCountry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICurrencyRepository_AddCountry_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool) error) *MockICurrencyRepository_AddCountry_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, currency
func (_m *MockICurrencyRepository) Create(ctx context.Context, currency *entity.Currency) error {
	ret := _m.Called(ctx, currency)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Currency) error); ok {
		r0 = rf(ctx, currency)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICurrencyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICurrencyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - currency *entity.Currency
func (_e *MockICurrencyRepository_Expecter) Create(ctx interface{}, currency interface{}) *MockICurrencyRepository_Create_Call {
	return &MockICurrencyRepository_Create_Call{Call: _e.mock.On("Create", ctx, currency)}
}

func (_c *MockICurrencyRepository_Create_Call) Run(run func(ctx context.Context, currency *entity.Currency)) *MockICurrencyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Currency))
	})
	return _c
}

func (_c *MockICurrencyRepository_Create_Call) Return(_a0 error) *MockICurrencyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICurrencyRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Currency) error) *MockICurrencyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockICurrencyRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICurrencyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICurrencyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockICurrencyRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockICurrencyRepository_Delete_Call {
	return &MockICurrencyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockICurrencyRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockICurrencyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICurrencyRepository_Delete_Call) Return(_a0 error) *MockICurrencyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICurrencyRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockICurrencyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function with given fields: ctx, code, withCountries
func (_m *MockICurrencyRepository) GetByCode(ctx context.Context, code string, withCountries bool) (*entity.Currency, error) {
	ret := _m.Called(ctx, code, withCountries)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*entity.Currency, error)); ok {
		return rf(ctx, code, withCountries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *entity.Currency); ok {
		r0 = rf(ctx, code, withCountries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, code, withCountries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICurrencyRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockICurrencyRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - withCountries bool
func (_e *MockICurrencyRepository_Expecter) GetByCode(ctx interface{}, code interface{}, withCountries interface{}) *MockICurrencyRepository_GetByCode_Call {
	return &MockICurrencyRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code, withCountries)}
}

func (_c *MockICurrencyRepository_GetByCode_Call) Run(run func(ctx context.Context, code string, withCountries bool)) *MockICurrencyRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockICurrencyRepository_GetByCode_Call) Return(_a0 *entity.Currency, _a1 error) *MockICurrencyRepository_GetByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICurrencyRepository_GetByCode_Call) RunAndReturn(run func(context.Context, string, bool) (*entity.Currency, error)) *MockICurrencyRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, withCountries
func (_m *MockICurrencyRepository) GetByID(ctx context.Context, id uuid.UUID, withCountries bool) (*entity.Currency, error) {
	ret := _m.Called(ctx, id, withCountries)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*entity.Currency, error)); ok {
		return rf(ctx, id, withCountries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *entity.Currency); ok {
		r0 = rf(ctx, id, withCountries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, id, withCountries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICurrencyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockICurrencyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - withCountries bool
func (_e *MockICurrencyRepository_Expecter) GetByID(ctx interface{}, id interface{}, withCountries interface{}) *MockICurrencyRepository_GetByID_Call {
	return &MockICurrencyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, withCountries)}
}

func (_c *MockICurrencyRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, withCountries bool)) *MockICurrencyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockICurrencyRepository_GetByID_Call) Return(_a0 *entity.Currency, _a1 error) *MockICurrencyRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICurrencyRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) (*entity.Currency, error)) *MockICurrencyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCountries provides a mock function with given fields: ctx, currencyID
func (_m *MockICurrencyRepository) GetCountries(ctx context.Context, currencyID uuid.UUID) ([]entity.Country, error) {
	ret := _m.Called(ctx, currencyID)

	if len(ret) == 0 {
		panic("no return value specified for GetCountries")
	}

	var r0 []entity.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Country, error)); ok {
		return rf(ctx, currencyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Country); ok {
		r0 = rf(ctx, currencyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, currencyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICurrencyRepository_GetCountries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCountries'
type MockICurrencyRepository_GetCountries_Call struct {
	*mock.Call
}

// GetCountries is a helper method to define mock.On call
//   - ctx context.Context
//   - currencyID uuid.UUID
func (_e *MockICurrencyRepository_Expecter) GetCountries(ctx interface{}, currencyID interface{}) *MockICurrencyRepository_GetCountries_Call {
	return &MockICurrencyRepository_GetCountries_Call{Call: _e.mock.On("GetCountries", ctx, currencyID)}
}

func (_c *MockICurrencyRepository_GetCountries_Call) Run(run func(ctx context.Context, currencyID uuid.UUID)) *MockICurrencyRepository_GetCountries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICurrencyRepository_GetCountries_Call) Return(_a0 []entity.Country, _a1 error) *MockICurrencyRepository_GetCountries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICurrencyRepository_GetCountries_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Country, error)) *MockICurrencyRepository_GetCountries_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit, withCountries
func (_m *MockICurrencyRepository) List(ctx context.Context, offset int, limit int, withCountries bool) ([]entity.Currency, int, error) {
	ret := _m.Called(ctx, offset, limit, withCountries)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Currency
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool) ([]entity.Currency, int, error)); ok {
		return rf(ctx, offset, limit, withCountries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool) []entity.Currency); ok {
		r0 = rf(ctx, offset, limit, withCountries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, bool) int); ok {
		r1 = rf(ctx, offset, limit, withCountries)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, bool) error); ok {
		r2 = rf(ctx, offset, limit, withCountries)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICurrencyRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockICurrencyRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - withCountries bool
func (_e *MockICurrencyRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}, withCountries interface{}) *MockICurrencyRepository_List_Call {
	return &MockICurrencyRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit, withCountries)}
}

func (_c *MockICurrencyRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int, withCountries bool)) *MockICurrencyRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(bool))
	})
	return _c
}

func (_c *MockICurrencyRepository_List_Call) Return(_a0 []entity.Currency, _a1 int, _a2 error) *MockICurrencyRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICurrencyRepository_List_Call) RunAndReturn(run func(context.Context, int, int, bool) ([]entity.Currency, int, error)) *MockICurrencyRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCountry provides a mock function with given fields: ctx, currencyID, countryID
func (_m *MockICurrencyRepository) RemoveCountry(ctx context.Context, currencyID uuid.UUID, countryID uuid.UUID) error {
	ret := _m.Called(ctx, currencyID, countryID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCountry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, currencyID, countryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICurrencyRepository_RemoveCountry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCountry'
type MockICurrencyRepository_RemoveCountry_Call struct {
	*mock.Call
}

// RemoveCountry is a helper method to define mock.On call
//   - ctx context.Context
//   - currencyID uuid.UUID
//   - countryID uuid.UUID
func (_e *MockICurrencyRepository_Expecter) RemoveCountry(ctx interface{}, currencyID interface{}, countryID interface{}) *MockICurrencyRepository_RemoveCountry_Call {
	return &MockICurrencyRepository_RemoveCountry_Call{Call: _e.mock.On("RemoveCountry", ctx, currencyID, countryID)}
}

func (_c *MockICurrencyRepository_RemoveCountry_Call) Run(run func(ctx context.Context, currencyID uuid.UUID, countryID uuid.UUID)) *MockICurrencyRepository_RemoveCountry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockICurrencyRepository_RemoveCountry_Call) Return(_a0 error) *MockICurrencyRepository_RemoveCountry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICurrencyRepository_RemoveCountry_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockICurrencyRepository_RemoveCountry_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, currency
func (_m *MockICurrencyRepository) Update(ctx context.Context, currency *entity.Currency) error {
	ret := _m.Called(ctx, currency)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Currency) error); ok {
		r0 = rf(ctx, currency)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICurrencyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICurrencyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - currency *entity.Currency
func (_e *MockICurrencyRepository_Expecter) Update(ctx interface{}, currency interface{}) *MockICurrencyRepository_Update_Call {
	return &MockICurrencyRepository_Update_Call{Call: _e.mock.On("Update", ctx, currency)}
}

func (_c *MockICurrencyRepository_Update_Call) Run(run func(ctx context.Context, currency *entity.Currency)) *MockICurrencyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Currency))
	})
	return _c
}

func (_c *MockICurrencyRepository_Update_Call) Return(_a0 error) *MockICurrencyRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICurrencyRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Currency) error) *MockICurrencyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICurrencyRepository creates a new instance of MockICurrencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICurrencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICurrencyRepository {
	mock := &MockICurrencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
