// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockICityRepository is an autogenerated mock type for the ICityRepository type
type MockICityRepository struct {
	mock.Mock
}

type MockICityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICityRepository) EXPECT() *MockICityRepository_Expecter {
	return &MockICityRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, city
func (_m *MockICityRepository) Create(ctx context.Context, city *entity.City) error {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.City) error); ok {
		r0 = rf(ctx, city)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICityRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - city *entity.City
func (_e *MockICityRepository_Expecter) Create(ctx interface{}, city interface{}) *MockICityRepository_Create_Call {
	return &MockICityRepository_Create_Call{Call: _e.mock.On("Create", ctx, city)}
}

func (_c *MockICityRepository_Create_Call) Run(run func(ctx context.Context, city *entity.City)) *MockICityRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.City))
	})
	return _c
}

func (_c *MockICityRepository_Create_Call) Return(_a0 error) *MockICityRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICityRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.City) error) *MockICityRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockICityRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICityRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICityRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockICityRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockICityRepository_Delete_Call {
	return &MockICityRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockICityRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockICityRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICityRepository_Delete_Call) Return(_a0 error) *MockICityRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICityRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockICityRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockICityRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.City, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.City
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.City, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.City); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICityRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockICityRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockICityRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockICityRepository_GetByID_Call {
	return &MockICityRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockICityRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockICityRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICityRepository_GetByID_Call) Return(_a0 *entity.City, _a1 error) *MockICityRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICityRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.City, error)) *MockICityRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *MockICityRepository) List(ctx context.Context, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.City); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICityRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockICityRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockICityRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockICityRepository_List_Call {
	return &MockICityRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockICityRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockICityRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockICityRepository_List_Call) Return(_a0 []entity.City, _a1 int, _a2 error) *MockICityRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICityRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]entity.City, int, error)) *MockICityRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx, offset, limit
func (_m *MockICityRepository) ListActive(ctx context.Context, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.City); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICityRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockICityRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockICityRepository_Expecter) ListActive(ctx interface{}, offset interface{}, limit interface{}) *MockICityRepository_ListActive_Call {
	return &MockICityRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx, offset, limit)}
}

func (_c *MockICityRepository_ListActive_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockICityRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockICityRepository_ListActive_Call) Return(_a0 []entity.City, _a1 int, _a2 error) *MockICityRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICityRepository_ListActive_Call) RunAndReturn(run func(context.Context, int, int) ([]entity.City, int, error)) *MockICityRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByCountry provides a mock function with given fields: ctx, countryID, offset, limit
func (_m *MockICityRepository) ListActiveByCountry(ctx context.Context, countryID uuid.UUID, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, countryID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByCountry")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, countryID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.City); ok {
		r0 = rf(ctx, countryID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, countryID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, countryID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICityRepository_ListActiveByCountry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByCountry'
type MockICityRepository_ListActiveByCountry_Call struct {
	*mock.Call
}

// ListActiveByCountry is a helper method to define mock.On call
//   - ctx context.Context
//   - countryID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockICityRepository_Expecter) ListActiveByCountry(ctx interface{}, countryID interface{}, offset interface{}, limit interface{}) *MockICityRepository_ListActiveByCountry_Call {
	return &MockICityRepository_ListActiveByCountry_Call{Call: _e.mock.On("ListActiveByCountry", ctx, countryID, offset, limit)}
}

func (_c *MockICityRepository_ListActiveByCountry_Call) Run(run func(ctx context.Context, countryID uuid.UUID, offset int, limit int)) *MockICityRepository_ListActiveByCountry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockICityRepository_ListActiveByCountry_Call) Return(_a0 []entity.City, _a1 int, _a2 error) *MockICityRepository_ListActiveByCountry_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICityRepository_ListActiveByCountry_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)) *MockICityRepository_ListActiveByCountry_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCountry provides a mock function with given fields: ctx, countryID, offset, limit
func (_m *MockICityRepository) ListByCountry(ctx context.Context, countryID uuid.UUID, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, countryID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByCountry")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, countryID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.City); ok {
		r0 = rf(ctx, countryID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, countryID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, countryID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICityRepository_ListByCountry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCountry'
type MockICityRepository_ListByCountry_Call struct {
	*mock.Call
}

// ListByCountry is a helper method to define mock.On call
//   - ctx context.Context
//   - countryID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockICityRepository_Expecter) ListByCountry(ctx interface{}, countryID interface{}, offset interface{}, limit interface{}) *MockICityRepository_ListByCountry_Call {
	return &MockICityRepository_ListByCountry_Call{Call: _e.mock.On("ListByCountry", ctx, countryID, offset, limit)}
}

func (_c *MockICityRepository_ListByCountry_Call) Run(run func(ctx context.Context, countryID uuid.UUID, offset int, limit int)) *MockICityRepository_ListByCountry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockICityRepository_ListByCountry_Call) Return(_a0 []entity.City, _a1 int, _a2 error) *MockICityRepository_ListByCountry_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICityRepository_ListByCountry_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)) *MockICityRepository_ListByCountry_Call {
	_c.Call.Return(run)
	return _c
}

// ListByRegion provides a mock function with given fields: ctx, regionID, offset, limit
func (_m *MockICityRepository) ListByRegion(ctx context.Context, regionID uuid.UUID, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, regionID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByRegion")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, regionID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.City); ok {
		r0 = rf(ctx, regionID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, regionID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, regionID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICityRepository_ListByRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByRegion'
type MockICityRepository_ListByRegion_Call struct {
	*mock.Call
}

// ListByRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - regionID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockICityRepository_Expecter) ListByRegion(ctx interface{}, regionID interface{}, offset interface{}, limit interface{}) *MockICityRepository_ListByRegion_Call {
	return &MockICityRepository_ListByRegion_Call{Call: _e.mock.On("ListByRegion", ctx, regionID, offset, limit)}
}

func (_c *MockICityRepository_ListByRegion_Call) Run(run func(ctx context.Context, regionID uuid.UUID, offset int, limit int)) *MockICityRepository_ListByRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockICityRepository_ListByRegion_Call) Return(_a0 []entity.City, _a1 int, _a2 error) *MockICityRepository_ListByRegion_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICityRepository_ListByRegion_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]entity.City, int, error)) *MockICityRepository_ListByRegion_Call {
	_c.Call.Return(run)
	return _c
}

// ListCapitals provides a mock function with given fields: ctx, offset, limit
func (_m *MockICityRepository) ListCapitals(ctx context.Context, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCapitals")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.City); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICityRepository_ListCapitals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCapitals'
type MockICityRepository_ListCapitals_Call struct {
	*mock.Call
}

// ListCapitals is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockICityRepository_Expecter) ListCapitals(ctx interface{}, offset interface{}, limit interface{}) *MockICityRepository_ListCapitals_Call {
	return &MockICityRepository_ListCapitals_Call{Call: _e.mock.On("ListCapitals", ctx, offset, limit)}
}

func (_c *MockICityRepository_ListCapitals_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockICityRepository_ListCapitals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockICityRepository_ListCapitals_Call) Return(_a0 []entity.City, _a1 int, _a2 error) *MockICityRepository_ListCapitals_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICityRepository_ListCapitals_Call) RunAndReturn(run func(context.Context, int, int) ([]entity.City, int, error)) *MockICityRepository_ListCapitals_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByName provides a mock function with given fields: ctx, query, offset, limit
func (_m *MockICityRepository) SearchByName(ctx context.Context, query string, offset int, limit int) ([]entity.City, int, error) {
	ret := _m.Called(ctx, query, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []entity.City
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]entity.City, int, error)); ok {
		return rf(ctx, query, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []entity.City); ok {
		r0 = rf(ctx, query, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.City)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, query, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, query, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICityRepository_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockICityRepository_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - offset int
//   - limit int
func (_e *MockICityRepository_Expecter) SearchByName(ctx interface{}, query interface{}, offset interface{}, limit interface{}) *MockICityRepository_SearchByName_Call {
	return &MockICityRepository_SearchByName_Call{Call: _e.mock.On("SearchByName", ctx, query, offset, limit)}
}

func (_c *MockICityRepository_SearchByName_Call) Run(run func(ctx context.Context, query string, offset int, limit int)) *MockICityRepository_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockICityRepository_SearchByName_Call) Return(_a0 []entity.City, _a1 int, _a2 error) *MockICityRepository_SearchByName_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICityRepository_SearchByName_Call) RunAndReturn(run func(context.Context, string, int, int) ([]entity.City, int, error)) *MockICityRepository_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, city
func (_m *MockICityRepository) Update(ctx context.Context, city *entity.City) error {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.City) error); ok {
		r0 = rf(ctx, city)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICityRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICityRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - city *entity.City
func (_e *MockICityRepository_Expecter) Update(ctx interface{}, city interface{}) *MockICityRepository_Update_Call {
	return &MockICityRepository_Update_Call{Call: _e.mock.On("Update", ctx, city)}
}

func (_c *MockICityRepository_Update_Call) Run(run func(ctx context.Context, city *entity.City)) *MockICityRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.City))
	})
	return _c
}

func (_c *MockICityRepository_Update_Call) Return(_a0 error) *MockICityRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICityRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.City) error) *MockICityRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICityRepository creates a new instance of MockICityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICityRepository {
	mock := &MockICityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
