// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockICountryRepository is an autogenerated mock type for the ICountryRepository type
type MockICountryRepository struct {
	mock.Mock
}

type MockICountryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICountryRepository) EXPECT() *MockICountryRepository_Expecter {
	return &MockICountryRepository_Expecter{mock: &_m.Mock}
}

// AddCurrency provides a mock function with given fields: ctx, countryID, currencyID, isPrimary
func (_m *MockICountryRepository) AddCurrency(ctx context.Context, countryID uuid.UUID, currencyID uuid.UUID, isPrimary bool) error {
	ret := _m.Called(ctx, countryID, currencyID, isPrimary)

	if len(ret) == 0 {
		panic("no return value specified for AddCurrency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, countryID, currencyID, isPrimary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICountryRepository_AddCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCurrency'
type MockICountryRepository_AddCurrency_Call struct {
	*mock.Call
}

// AddCurrency is a helper method to define mock.On call
//   - ctx context.Context
//   - countryID uuid.UUID
//   - currencyID uuid.UUID
//   - isPrimary bool
func (_e *MockICountryRepository_Expecter) AddCurrency(ctx interface{}, countryID interface{}, currencyID interface{}, isPrimary interface{}) *MockICountryRepository_AddCurrency_Call {
	return &MockICountryRepository_AddCurrency_Call{Call: _e.mock.On("AddCurrency", ctx, countryID, currencyID, isPrimary)}
}

func (_c *MockICountryRepository_AddCurrency_Call) Run(run func(ctx context.Context, countryID uuid.UUID, currencyID uuid.UUID, isPrimary bool)) *MockICountryRepository_AddCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockICountryRepository_AddCurrency_Call) Return(_a0 error) *MockICountryRepository_AddCurrency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICountryRepository_AddCurrency_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool) error) *MockICountryRepository_AddCurrency_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, country
func (_m *MockICountryRepository) Create(ctx context.Context, country *entity.Country) error {
	ret := _m.Called(ctx, country)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Country) error); ok {
		r0 = rf(ctx, country)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICountryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICountryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - country *entity.Country
func (_e *MockICountryRepository_Expecter) Create(ctx interface{}, country interface{}) *MockICountryRepository_Create_Call {
	return &MockICountryRepository_Create_Call{Call: _e.mock.On("Create", ctx, country)}
}

func (_c *MockICountryRepository_Create_Call) Run(run func(ctx context.Context, country *entity.Country)) *MockICountryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Country))
	})
	return _c
}

func (_c *MockICountryRepository_Create_Call) Return(_a0 error) *MockICountryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICountryRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Country) error) *MockICountryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockICountryRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICountryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICountryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockICountryRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockICountryRepository_Delete_Call {
	return &MockICountryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockICountryRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockICountryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICountryRepository_Delete_Call) Return(_a0 error) *MockICountryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICountryRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockICountryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function with given fields: ctx, code, withCurrencies
func (_m *MockICountryRepository) GetByCode(ctx context.Context, code string, withCurrencies bool) (*entity.Country, error) {
	ret := _m.Called(ctx, code, withCurrencies)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*entity.Country, error)); ok {
		return rf(ctx, code, withCurrencies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *entity.Country); ok {
		r0 = rf(ctx, code, withCurrencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, code, withCurrencies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICountryRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockICountryRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - withCurrencies bool
func (_e *MockICountryRepository_Expecter) GetByCode(ctx interface{}, code interface{}, withCurrencies interface{}) *MockICountryRepository_GetByCode_Call {
	return &MockICountryRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code, withCurrencies)}
}

func (_c *MockICountryRepository_GetByCode_Call) Run(run func(ctx context.Context, code string, withCurrencies bool)) *MockICountryRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockICountryRepository_GetByCode_Call) Return(_a0 *entity.Country, _a1 error) *MockICountryRepository_GetByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICountryRepository_GetByCode_Call) RunAndReturn(run func(context.Context, string, bool) (*entity.Country, error)) *MockICountryRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id, withCurrencies
func (_m *MockICountryRepository) GetByID(ctx context.Context, id uuid.UUID, withCurrencies bool) (*entity.Country, error) {
	ret := _m.Called(ctx, id, withCurrencies)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Country
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*entity.Country, error)); ok {
		return rf(ctx, id, withCurrencies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *entity.Country); ok {
		r0 = rf(ctx, id, withCurrencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, id, withCurrencies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICountryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockICountryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - withCurrencies bool
func (_e *MockICountryRepository_Expecter) GetByID(ctx interface{}, id interface{}, withCurrencies interface{}) *MockICountryRepository_GetByID_Call {
	return &MockICountryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id, withCurrencies)}
}

func (_c *MockICountryRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, withCurrencies bool)) *MockICountryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockICountryRepository_GetByID_Call) Return(_a0 *entity.Country, _a1 error) *MockICountryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICountryRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) (*entity.Country, error)) *MockICountryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrencies provides a mock function with given fields: ctx, countryID
func (_m *MockICountryRepository) GetCurrencies(ctx context.Context, countryID uuid.UUID) ([]entity.Currency, error) {
	ret := _m.Called(ctx, countryID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencies")
	}

	var r0 []entity.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]entity.Currency, error)); ok {
		return rf(ctx, countryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []entity.Currency); ok {
		r0 = rf(ctx, countryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, countryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICountryRepository_GetCurrencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrencies'
type MockICountryRepository_GetCurrencies_Call struct {
	*mock.Call
}

// GetCurrencies is a helper method to define mock.On call
//   - ctx context.Context
//   - countryID uuid.UUID
func (_e *MockICountryRepository_Expecter) GetCurrencies(ctx interface{}, countryID interface{}) *MockICountryRepository_GetCurrencies_Call {
	return &MockICountryRepository_GetCurrencies_Call{Call: _e.mock.On("GetCurrencies", ctx, countryID)}
}

func (_c *MockICountryRepository_GetCurrencies_Call) Run(run func(ctx context.Context, countryID uuid.UUID)) *MockICountryRepository_GetCurrencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICountryRepository_GetCurrencies_Call) Return(_a0 []entity.Currency, _a1 error) *MockICountryRepository_GetCurrencies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICountryRepository_GetCurrencies_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]entity.Currency, error)) *MockICountryRepository_GetCurrencies_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit, withCurrencies
func (_m *MockICountryRepository) List(ctx context.Context, offset int, limit int, withCurrencies bool) ([]entity.Country, int, error) {
	ret := _m.Called(ctx, offset, limit, withCurrencies)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Country
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool) ([]entity.Country, int, error)); ok {
		return rf(ctx, offset, limit, withCurrencies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, bool) []entity.Country); ok {
		r0 = rf(ctx, offset, limit, withCurrencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, bool) int); ok {
		r1 = rf(ctx, offset, limit, withCurrencies)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, bool) error); ok {
		r2 = rf(ctx, offset, limit, withCurrencies)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICountryRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockICountryRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - withCurrencies bool
func (_e *MockICountryRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}, withCurrencies interface{}) *MockICountryRepository_List_Call {
	return &MockICountryRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit, withCurrencies)}
}

func (_c *MockICountryRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int, withCurrencies bool)) *MockICountryRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(bool))
	})
	return _c
}

func (_c *MockICountryRepository_List_Call) Return(_a0 []entity.Country, _a1 int, _a2 error) *MockICountryRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICountryRepository_List_Call) RunAndReturn(run func(context.Context, int, int, bool) ([]entity.Country, int, error)) *MockICountryRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByRegion provides a mock function with given fields: ctx, region, offset, limit, withCurrencies
func (_m *MockICountryRepository) ListByRegion(ctx context.Context, region string, offset int, limit int, withCurrencies bool) ([]entity.Country, int, error) {
	ret := _m.Called(ctx, region, offset, limit, withCurrencies)

	if len(ret) == 0 {
		panic("no return value specified for ListByRegion")
	}

	var r0 []entity.Country
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) ([]entity.Country, int, error)); ok {
		return rf(ctx, region, offset, limit, withCurrencies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) []entity.Country); ok {
		r0 = rf(ctx, region, offset, limit, withCurrencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Country)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, bool) int); ok {
		r1 = rf(ctx, region, offset, limit, withCurrencies)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, bool) error); ok {
		r2 = rf(ctx, region, offset, limit, withCurrencies)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICountryRepository_ListByRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByRegion'
type MockICountryRepository_ListByRegion_Call struct {
	*mock.Call
}

// ListByRegion is a helper method to define mock.On call
//   - ctx context.Context
//   - region string
//   - offset int
//   - limit int
//   - withCurrencies bool
func (_e *MockICountryRepository_Expecter) ListByRegion(ctx interface{}, region interface{}, offset interface{}, limit interface{}, withCurrencies interface{}) *MockICountryRepository_ListByRegion_Call {
	return &MockICountryRepository_ListByRegion_Call{Call: _e.mock.On("ListByRegion", ctx, region, offset, limit, withCurrencies)}
}

func (_c *MockICountryRepository_ListByRegion_Call) Run(run func(ctx context.Context, region string, offset int, limit int, withCurrencies bool)) *MockICountryRepository_ListByRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(bool))
	})
	return _c
}

func (_c *MockICountryRepository_ListByRegion_Call) Return(_a0 []entity.Country, _a1 int, _a2 error) *MockICountryRepository_ListByRegion_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICountryRepository_ListByRegion_Call) RunAndReturn(run func(context.Context, string, int, int, bool) ([]entity.Country, int, error)) *MockICountryRepository_ListByRegion_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCurrency provides a mock function with given fields: ctx, countryID, currencyID
func (_m *MockICountryRepository) RemoveCurrency(ctx context.Context, countryID uuid.UUID, currencyID uuid.UUID) error {
	ret := _m.Called(ctx, countryID, currencyID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCurrency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, countryID, currencyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICountryRepository_RemoveCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCurrency'
type MockICountryRepository_RemoveCurrency_Call struct {
	*mock.Call
}

// RemoveCurrency is a helper method to define mock.On call
//   - ctx context.Context
//   - countryID uuid.UUID
//   - currencyID uuid.UUID
func (_e *MockICountryRepository_Expecter) RemoveCurrency(ctx interface{}, countryID interface{}, currencyID interface{}) *MockICountryRepository_RemoveCurrency_Call {
	return &MockICountryRepository_RemoveCurrency_Call{Call: _e.mock.On("RemoveCurrency", ctx, countryID, currencyID)}
}

func (_c *MockICountryRepository_RemoveCurrency_Call) Run(run func(ctx context.Context, countryID uuid.UUID, currencyID uuid.UUID)) *MockICountryRepository_RemoveCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockICountryRepository_RemoveCurrency_Call) Return(_a0 error) *MockICountryRepository_RemoveCurrency_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICountryRepository_RemoveCurrency_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockICountryRepository_RemoveCurrency_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, country
func (_m *MockICountryRepository) Update(ctx context.Context, country *entity.Country) error {
	ret := _m.Called(ctx, country)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Country) error); ok {
		r0 = rf(ctx, country)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICountryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICountryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - country *entity.Country
func (_e *MockICountryRepository_Expecter) Update(ctx interface{}, country interface{}) *MockICountryRepository_Update_Call {
	return &MockICountryRepository_Update_Call{Call: _e.mock.On("Update", ctx, country)}
}

func (_c *MockICountryRepository_Update_Call) Run(run func(ctx context.Context, country *entity.Country)) *MockICountryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Country))
	})
	return _c
}

func (_c *MockICountryRepository_Update_Call) Return(_a0 error) *MockICountryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICountryRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Country) error) *MockICountryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICountryRepository creates a new instance of MockICountryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICountryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICountryRepository {
	mock := &MockICountryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
