// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIRegionRepository is an autogenerated mock type for the IRegionRepository type
type MockIRegionRepository struct {
	mock.Mock
}

type MockIRegionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRegionRepository) EXPECT() *MockIRegionRepository_Expecter {
	return &MockIRegionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, region
func (_m *MockIRegionRepository) Create(ctx context.Context, region *entity.Region) error {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Region) error); ok {
		r0 = rf(ctx, region)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRegionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRegionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - region *entity.Region
func (_e *MockIRegionRepository_Expecter) Create(ctx interface{}, region interface{}) *MockIRegionRepository_Create_Call {
	return &MockIRegionRepository_Create_Call{Call: _e.mock.On("Create", ctx, region)}
}

func (_c *MockIRegionRepository_Create_Call) Run(run func(ctx context.Context, region *entity.Region)) *MockIRegionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Region))
	})
	return _c
}

func (_c *MockIRegionRepository_Create_Call) Return(_a0 error) *MockIRegionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRegionRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Region) error) *MockIRegionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIRegionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRegionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIRegionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIRegionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockIRegionRepository_Delete_Call {
	return &MockIRegionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIRegionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIRegionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRegionRepository_Delete_Call) Return(_a0 error) *MockIRegionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRegionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIRegionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function with given fields: ctx, countryID, code
func (_m *MockIRegionRepository) GetByCode(ctx context.Context, countryID uuid.UUID, code string) (*entity.Region, error) {
	ret := _m.Called(ctx, countryID, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Region
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entity.Region, error)); ok {
		return rf(ctx, countryID, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entity.Region); ok {
		r0 = rf(ctx, countryID, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Region)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, countryID, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRegionRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockIRegionRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - countryID uuid.UUID
//   - code string
func (_e *MockIRegionRepository_Expecter) GetByCode(ctx interface{}, countryID interface{}, code interface{}) *MockIRegionRepository_GetByCode_Call {
	return &MockIRegionRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, countryID, code)}
}

func (_c *MockIRegionRepository_GetByCode_Call) Run(run func(ctx context.Context, countryID uuid.UUID, code string)) *MockIRegionRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIRegionRepository_GetByCode_Call) Return(_a0 *entity.Region, _a1 error) *MockIRegionRepository_GetByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRegionRepository_GetByCode_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*entity.Region, error)) *MockIRegionRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIRegionRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Region, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Region
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Region, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Region); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Region)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRegionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIRegionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIRegionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIRegionRepository_GetByID_Call {
	return &MockIRegionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIRegionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIRegionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRegionRepository_GetByID_Call) Return(_a0 *entity.Region, _a1 error) *MockIRegionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRegionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Region, error)) *MockIRegionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *MockIRegionRepository) List(ctx context.Context, offset int, limit int) ([]entity.Region, int, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entity.Region
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.Region, int, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.Region); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Region)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRegionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIRegionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockIRegionRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockIRegionRepository_List_Call {
	return &MockIRegionRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockIRegionRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockIRegionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIRegionRepository_List_Call) Return(_a0 []entity.Region, _a1 int, _a2 error) *MockIRegionRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRegionRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]entity.Region, int, error)) *MockIRegionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx, offset, limit
func (_m *MockIRegionRepository) ListActive(ctx context.Context, offset int, limit int) ([]entity.Region, int, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []entity.Region
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]entity.Region, int, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []entity.Region); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Region)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRegionRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockIRegionRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockIRegionRepository_Expecter) ListActive(ctx interface{}, offset interface{}, limit interface{}) *MockIRegionRepository_ListActive_Call {
	return &MockIRegionRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx, offset, limit)}
}

func (_c *MockIRegionRepository_ListActive_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockIRegionRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIRegionRepository_ListActive_Call) Return(_a0 []entity.Region, _a1 int, _a2 error) *MockIRegionRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRegionRepository_ListActive_Call) RunAndReturn(run func(context.Context, int, int) ([]entity.Region, int, error)) *MockIRegionRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByCountry provides a mock function with given fields: ctx, countryID, offset, limit
func (_m *MockIRegionRepository) ListActiveByCountry(ctx context.Context, countryID uuid.UUID, offset int, limit int) ([]entity.Region, int, error) {
	ret := _m.Called(ctx, countryID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByCountry")
	}

	var r0 []entity.Region
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.Region, int, error)); ok {
		return rf(ctx, countryID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.Region); ok {
		r0 = rf(ctx, countryID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Region)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, countryID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, countryID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRegionRepository_ListActiveByCountry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByCountry'
type MockIRegionRepository_ListActiveByCountry_Call struct {
	*mock.Call
}

// ListActiveByCountry is a helper method to define mock.On call
//   - ctx context.Context
//   - countryID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockIRegionRepository_Expecter) ListActiveByCountry(ctx interface{}, countryID interface{}, offset interface{}, limit interface{}) *MockIRegionRepository_ListActiveByCountry_Call {
	return &MockIRegionRepository_ListActiveByCountry_Call{Call: _e.mock.On("ListActiveByCountry", ctx, countryID, offset, limit)}
}

func (_c *MockIRegionRepository_ListActiveByCountry_Call) Run(run func(ctx context.Context, countryID uuid.UUID, offset int, limit int)) *MockIRegionRepository_ListActiveByCountry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIRegionRepository_ListActiveByCountry_Call) Return(_a0 []entity.Region, _a1 int, _a2 error) *MockIRegionRepository_ListActiveByCountry_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRegionRepository_ListActiveByCountry_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]entity.Region, int, error)) *MockIRegionRepository_ListActiveByCountry_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCountry provides a mock function with given fields: ctx, countryID, offset, limit
func (_m *MockIRegionRepository) ListByCountry(ctx context.Context, countryID uuid.UUID, offset int, limit int) ([]entity.Region, int, error) {
	ret := _m.Called(ctx, countryID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListByCountry")
	}

	var r0 []entity.Region
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]entity.Region, int, error)); ok {
		return rf(ctx, countryID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []entity.Region); ok {
		r0 = rf(ctx, countryID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Region)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = rf(ctx, countryID, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, countryID, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIRegionRepository_ListByCountry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCountry'
type MockIRegionRepository_ListByCountry_Call struct {
	*mock.Call
}

// ListByCountry is a helper method to define mock.On call
//   - ctx context.Context
//   - countryID uuid.UUID
//   - offset int
//   - limit int
func (_e *MockIRegionRepository_Expecter) ListByCountry(ctx interface{}, countryID interface{}, offset interface{}, limit interface{}) *MockIRegionRepository_ListByCountry_Call {
	return &MockIRegionRepository_ListByCountry_Call{Call: _e.mock.On("ListByCountry", ctx, countryID, offset, limit)}
}

func (_c *MockIRegionRepository_ListByCountry_Call) Run(run func(ctx context.Context, countryID uuid.UUID, offset int, limit int)) *MockIRegionRepository_ListByCountry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIRegionRepository_ListByCountry_Call) Return(_a0 []entity.Region, _a1 int, _a2 error) *MockIRegionRepository_ListByCountry_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIRegionRepository_ListByCountry_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]entity.Region, int, error)) *MockIRegionRepository_ListByCountry_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, region
func (_m *MockIRegionRepository) Update(ctx context.Context, region *entity.Region) error {
	ret := _m.Called(ctx, region)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Region) error); ok {
		r0 = rf(ctx, region)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRegionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIRegionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - region *entity.Region
func (_e *MockIRegionRepository_Expecter) Update(ctx interface{}, region interface{}) *MockIRegionRepository_Update_Call {
	return &MockIRegionRepository_Update_Call{Call: _e.mock.On("Update", ctx, region)}
}

func (_c *MockIRegionRepository_Update_Call) Run(run func(ctx context.Context, region *entity.Region)) *MockIRegionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Region))
	})
	return _c
}

func (_c *MockIRegionRepository_Update_Call) Return(_a0 error) *MockIRegionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRegionRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Region) error) *MockIRegionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRegionRepository creates a new instance of MockIRegionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRegionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRegionRepository {
	mock := &MockIRegionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
