// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIRoleRepository is an autogenerated mock type for the IRoleRepository type
type MockIRoleRepository struct {
	mock.Mock
}

type MockIRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRoleRepository) EXPECT() *MockIRoleRepository_Expecter {
	return &MockIRoleRepository_Expecter{mock: &_m.Mock}
}

// AddPermission provides a mock function with given fields: ctx, roleID, permissionID
func (_m *MockIRoleRepository) AddPermission(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) error {
	ret := _m.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for AddPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roleID, permissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_AddPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPermission'
type MockIRoleRepository_AddPermission_Call struct {
	*mock.Call
}

// AddPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionID uuid.UUID
func (_e *MockIRoleRepository_Expecter) AddPermission(ctx interface{}, roleID interface{}, permissionID interface{}) *MockIRoleRepository_AddPermission_Call {
	return &MockIRoleRepository_AddPermission_Call{Call: _e.mock.On("AddPermission", ctx, roleID, permissionID)}
}

func (_c *MockIRoleRepository_AddPermission_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID)) *MockIRoleRepository_AddPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_AddPermission_Call) Return(_a0 error) *MockIRoleRepository_AddPermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_AddPermission_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockIRoleRepository_AddPermission_Call {
	_c.Call.Return(run)
	return _c
}

// AssignToUser provides a mock function with given fields: ctx, userRole
func (_m *MockIRoleRepository) AssignToUser(ctx context.Context, userRole *entity.UserRole) error {
	ret := _m.Called(ctx, userRole)

	if len(ret) == 0 {
		panic("no return value specified for AssignToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserRole) error); ok {
		r0 = rf(ctx, userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_AssignToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignToUser'
type MockIRoleRepository_AssignToUser_Call struct {
	*mock.Call
}

// AssignToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userRole *entity.UserRole
func (_e *MockIRoleRepository_Expecter) AssignToUser(ctx interface{}, userRole interface{}) *MockIRoleRepository_AssignToUser_Call {
	return &MockIRoleRepository_AssignToUser_Call{Call: _e.mock.On("AssignToUser", ctx, userRole)}
}

func (_c *MockIRoleRepository_AssignToUser_Call) Run(run func(ctx context.Context, userRole *entity.UserRole)) *MockIRoleRepository_AssignToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserRole))
	})
	return _c
}

func (_c *MockIRoleRepository_AssignToUser_Call) Return(_a0 error) *MockIRoleRepository_AssignToUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_AssignToUser_Call) RunAndReturn(run func(context.Context, *entity.UserRole) error) *MockIRoleRepository_AssignToUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, role
func (_m *MockIRoleRepository) Create(ctx context.Context, role *entity.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - role *entity.Role
func (_e *MockIRoleRepository_Expecter) Create(ctx interface{}, role interface{}) *MockIRoleRepository_Create_Call {
	return &MockIRoleRepository_Create_Call{Call: _e.mock.On("Create", ctx, role)}
}

func (_c *MockIRoleRepository_Create_Call) Run(run func(ctx context.Context, role *entity.Role)) *MockIRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Role))
	})
	return _c
}

func (_c *MockIRoleRepository_Create_Call) Return(_a0 error) *MockIRoleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Role) error) *MockIRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMany provides a mock function with given fields: ctx, roles
func (_m *MockIRoleRepository) CreateMany(ctx context.Context, roles []*entity.Role) error {
	ret := _m.Called(ctx, roles)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entity.Role) error); ok {
		r0 = rf(ctx, roles)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_CreateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMany'
type MockIRoleRepository_CreateMany_Call struct {
	*mock.Call
}

// CreateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - roles []*entity.Role
func (_e *MockIRoleRepository_Expecter) CreateMany(ctx interface{}, roles interface{}) *MockIRoleRepository_CreateMany_Call {
	return &MockIRoleRepository_CreateMany_Call{Call: _e.mock.On("CreateMany", ctx, roles)}
}

func (_c *MockIRoleRepository_CreateMany_Call) Run(run func(ctx context.Context, roles []*entity.Role)) *MockIRoleRepository_CreateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*entity.Role))
	})
	return _c
}

func (_c *MockIRoleRepository_CreateMany_Call) Return(_a0 error) *MockIRoleRepository_CreateMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_CreateMany_Call) RunAndReturn(run func(context.Context, []*entity.Role) error) *MockIRoleRepository_CreateMany_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIRoleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIRoleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockIRoleRepository_Delete_Call {
	return &MockIRoleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIRoleRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_Delete_Call) Return(_a0 error) *MockIRoleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIRoleRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRoleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIRoleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIRoleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIRoleRepository_GetByID_Call {
	return &MockIRoleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIRoleRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIRoleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_GetByID_Call) Return(_a0 *entity.Role, _a1 error) *MockIRoleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRoleRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Role, error)) *MockIRoleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockIRoleRepository) GetByName(ctx context.Context, name string) (*entity.Role, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Role, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Role); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRoleRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockIRoleRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockIRoleRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockIRoleRepository_GetByName_Call {
	return &MockIRoleRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockIRoleRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockIRoleRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIRoleRepository_GetByName_Call) Return(_a0 *entity.Role, _a1 error) *MockIRoleRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRoleRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*entity.Role, error)) *MockIRoleRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetPermissions provides a mock function with given fields: ctx, roleID
func (_m *MockIRoleRepository) GetPermissions(ctx context.Context, roleID uuid.UUID) ([]*entity.Permission, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetPermissions")
	}

	var r0 []*entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Permission, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Permission); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRoleRepository_GetPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPermissions'
type MockIRoleRepository_GetPermissions_Call struct {
	*mock.Call
}

// GetPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
func (_e *MockIRoleRepository_Expecter) GetPermissions(ctx interface{}, roleID interface{}) *MockIRoleRepository_GetPermissions_Call {
	return &MockIRoleRepository_GetPermissions_Call{Call: _e.mock.On("GetPermissions", ctx, roleID)}
}

func (_c *MockIRoleRepository_GetPermissions_Call) Run(run func(ctx context.Context, roleID uuid.UUID)) *MockIRoleRepository_GetPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_GetPermissions_Call) Return(_a0 []*entity.Permission, _a1 error) *MockIRoleRepository_GetPermissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRoleRepository_GetPermissions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Permission, error)) *MockIRoleRepository_GetPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserActiveRoles provides a mock function with given fields: ctx, userID
func (_m *MockIRoleRepository) GetUserActiveRoles(ctx context.Context, userID uuid.UUID) ([]*entity.Role, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserActiveRoles")
	}

	var r0 []*entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Role, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Role); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRoleRepository_GetUserActiveRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserActiveRoles'
type MockIRoleRepository_GetUserActiveRoles_Call struct {
	*mock.Call
}

// GetUserActiveRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockIRoleRepository_Expecter) GetUserActiveRoles(ctx interface{}, userID interface{}) *MockIRoleRepository_GetUserActiveRoles_Call {
	return &MockIRoleRepository_GetUserActiveRoles_Call{Call: _e.mock.On("GetUserActiveRoles", ctx, userID)}
}

func (_c *MockIRoleRepository_GetUserActiveRoles_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockIRoleRepository_GetUserActiveRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_GetUserActiveRoles_Call) Return(_a0 []*entity.Role, _a1 error) *MockIRoleRepository_GetUserActiveRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRoleRepository_GetUserActiveRoles_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Role, error)) *MockIRoleRepository_GetUserActiveRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRoles provides a mock function with given fields: ctx, userID
func (_m *MockIRoleRepository) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]*entity.Role, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRoles")
	}

	var r0 []*entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Role, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Role); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRoleRepository_GetUserRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRoles'
type MockIRoleRepository_GetUserRoles_Call struct {
	*mock.Call
}

// GetUserRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockIRoleRepository_Expecter) GetUserRoles(ctx interface{}, userID interface{}) *MockIRoleRepository_GetUserRoles_Call {
	return &MockIRoleRepository_GetUserRoles_Call{Call: _e.mock.On("GetUserRoles", ctx, userID)}
}

func (_c *MockIRoleRepository_GetUserRoles_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockIRoleRepository_GetUserRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_GetUserRoles_Call) Return(_a0 []*entity.Role, _a1 error) *MockIRoleRepository_GetUserRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRoleRepository_GetUserRoles_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Role, error)) *MockIRoleRepository_GetUserRoles_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithRole provides a mock function with given fields: ctx, roleID
func (_m *MockIRoleRepository) GetUsersWithRole(ctx context.Context, roleID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithRole")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, roleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRoleRepository_GetUsersWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithRole'
type MockIRoleRepository_GetUsersWithRole_Call struct {
	*mock.Call
}

// GetUsersWithRole is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
func (_e *MockIRoleRepository_Expecter) GetUsersWithRole(ctx interface{}, roleID interface{}) *MockIRoleRepository_GetUsersWithRole_Call {
	return &MockIRoleRepository_GetUsersWithRole_Call{Call: _e.mock.On("GetUsersWithRole", ctx, roleID)}
}

func (_c *MockIRoleRepository_GetUsersWithRole_Call) Run(run func(ctx context.Context, roleID uuid.UUID)) *MockIRoleRepository_GetUsersWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_GetUsersWithRole_Call) Return(_a0 []uuid.UUID, _a1 error) *MockIRoleRepository_GetUsersWithRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRoleRepository_GetUsersWithRole_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *MockIRoleRepository_GetUsersWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockIRoleRepository) List(ctx context.Context) ([]*entity.Role, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Role, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Role); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIRoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIRoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIRoleRepository_Expecter) List(ctx interface{}) *MockIRoleRepository_List_Call {
	return &MockIRoleRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockIRoleRepository_List_Call) Run(run func(ctx context.Context)) *MockIRoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIRoleRepository_List_Call) Return(_a0 []*entity.Role, _a1 error) *MockIRoleRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIRoleRepository_List_Call) RunAndReturn(run func(context.Context) ([]*entity.Role, error)) *MockIRoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFromUser provides a mock function with given fields: ctx, userID, roleID
func (_m *MockIRoleRepository) RemoveFromUser(ctx context.Context, userID uuid.UUID, roleID uuid.UUID) error {
	ret := _m.Called(ctx, userID, roleID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userID, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_RemoveFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFromUser'
type MockIRoleRepository_RemoveFromUser_Call struct {
	*mock.Call
}

// RemoveFromUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - roleID uuid.UUID
func (_e *MockIRoleRepository_Expecter) RemoveFromUser(ctx interface{}, userID interface{}, roleID interface{}) *MockIRoleRepository_RemoveFromUser_Call {
	return &MockIRoleRepository_RemoveFromUser_Call{Call: _e.mock.On("RemoveFromUser", ctx, userID, roleID)}
}

func (_c *MockIRoleRepository_RemoveFromUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, roleID uuid.UUID)) *MockIRoleRepository_RemoveFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_RemoveFromUser_Call) Return(_a0 error) *MockIRoleRepository_RemoveFromUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_RemoveFromUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockIRoleRepository_RemoveFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermission provides a mock function with given fields: ctx, roleID, permissionID
func (_m *MockIRoleRepository) RemovePermission(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID) error {
	ret := _m.Called(ctx, roleID, permissionID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roleID, permissionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_RemovePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermission'
type MockIRoleRepository_RemovePermission_Call struct {
	*mock.Call
}

// RemovePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionID uuid.UUID
func (_e *MockIRoleRepository_Expecter) RemovePermission(ctx interface{}, roleID interface{}, permissionID interface{}) *MockIRoleRepository_RemovePermission_Call {
	return &MockIRoleRepository_RemovePermission_Call{Call: _e.mock.On("RemovePermission", ctx, roleID, permissionID)}
}

func (_c *MockIRoleRepository_RemovePermission_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionID uuid.UUID)) *MockIRoleRepository_RemovePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_RemovePermission_Call) Return(_a0 error) *MockIRoleRepository_RemovePermission_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_RemovePermission_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockIRoleRepository_RemovePermission_Call {
	_c.Call.Return(run)
	return _c
}

// SyncPermissions provides a mock function with given fields: ctx, roleID, permissionIDs
func (_m *MockIRoleRepository) SyncPermissions(ctx context.Context, roleID uuid.UUID, permissionIDs []uuid.UUID) error {
	ret := _m.Called(ctx, roleID, permissionIDs)

	if len(ret) == 0 {
		panic("no return value specified for SyncPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, roleID, permissionIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_SyncPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncPermissions'
type MockIRoleRepository_SyncPermissions_Call struct {
	*mock.Call
}

// SyncPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permissionIDs []uuid.UUID
func (_e *MockIRoleRepository_Expecter) SyncPermissions(ctx interface{}, roleID interface{}, permissionIDs interface{}) *MockIRoleRepository_SyncPermissions_Call {
	return &MockIRoleRepository_SyncPermissions_Call{Call: _e.mock.On("SyncPermissions", ctx, roleID, permissionIDs)}
}

func (_c *MockIRoleRepository_SyncPermissions_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permissionIDs []uuid.UUID)) *MockIRoleRepository_SyncPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]uuid.UUID))
	})
	return _c
}

func (_c *MockIRoleRepository_SyncPermissions_Call) Return(_a0 error) *MockIRoleRepository_SyncPermissions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_SyncPermissions_Call) RunAndReturn(run func(context.Context, uuid.UUID, []uuid.UUID) error) *MockIRoleRepository_SyncPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, role
func (_m *MockIRoleRepository) Update(ctx context.Context, role *entity.Role) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Role) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - role *entity.Role
func (_e *MockIRoleRepository_Expecter) Update(ctx interface{}, role interface{}) *MockIRoleRepository_Update_Call {
	return &MockIRoleRepository_Update_Call{Call: _e.mock.On("Update", ctx, role)}
}

func (_c *MockIRoleRepository_Update_Call) Run(run func(ctx context.Context, role *entity.Role)) *MockIRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Role))
	})
	return _c
}

func (_c *MockIRoleRepository_Update_Call) Return(_a0 error) *MockIRoleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRoleRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Role) error) *MockIRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRoleRepository creates a new instance of MockIRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRoleRepository {
	mock := &MockIRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
