// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/basilex/promenade/pkg/pagination"

	uuid "github.com/google/uuid"
)

// MockILanguageRepository is an autogenerated mock type for the ILanguageRepository type
type MockILanguageRepository struct {
	mock.Mock
}

type MockILanguageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILanguageRepository) EXPECT() *MockILanguageRepository_Expecter {
	return &MockILanguageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, language
func (_m *MockILanguageRepository) Create(ctx context.Context, language *entity.Language) error {
	ret := _m.Called(ctx, language)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Language) error); ok {
		r0 = rf(ctx, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockILanguageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockILanguageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - language *entity.Language
func (_e *MockILanguageRepository_Expecter) Create(ctx interface{}, language interface{}) *MockILanguageRepository_Create_Call {
	return &MockILanguageRepository_Create_Call{Call: _e.mock.On("Create", ctx, language)}
}

func (_c *MockILanguageRepository_Create_Call) Run(run func(ctx context.Context, language *entity.Language)) *MockILanguageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Language))
	})
	return _c
}

func (_c *MockILanguageRepository_Create_Call) Return(_a0 error) *MockILanguageRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockILanguageRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Language) error) *MockILanguageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockILanguageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockILanguageRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockILanguageRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockILanguageRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockILanguageRepository_Delete_Call {
	return &MockILanguageRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockILanguageRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockILanguageRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockILanguageRepository_Delete_Call) Return(_a0 error) *MockILanguageRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockILanguageRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockILanguageRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, code
func (_m *MockILanguageRepository) Exists(ctx context.Context, code string) (bool, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockILanguageRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockILanguageRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockILanguageRepository_Expecter) Exists(ctx interface{}, code interface{}) *MockILanguageRepository_Exists_Call {
	return &MockILanguageRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, code)}
}

func (_c *MockILanguageRepository_Exists_Call) Run(run func(ctx context.Context, code string)) *MockILanguageRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockILanguageRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockILanguageRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockILanguageRepository_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockILanguageRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *MockILanguageRepository) GetByCode(ctx context.Context, code string) (*entity.Language, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Language, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Language); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockILanguageRepository_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockILanguageRepository_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockILanguageRepository_Expecter) GetByCode(ctx interface{}, code interface{}) *MockILanguageRepository_GetByCode_Call {
	return &MockILanguageRepository_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *MockILanguageRepository_GetByCode_Call) Run(run func(ctx context.Context, code string)) *MockILanguageRepository_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockILanguageRepository_GetByCode_Call) Return(_a0 *entity.Language, _a1 error) *MockILanguageRepository_GetByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockILanguageRepository_GetByCode_Call) RunAndReturn(run func(context.Context, string) (*entity.Language, error)) *MockILanguageRepository_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockILanguageRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Language, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Language, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Language); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockILanguageRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockILanguageRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockILanguageRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockILanguageRepository_GetByID_Call {
	return &MockILanguageRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockILanguageRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockILanguageRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockILanguageRepository_GetByID_Call) Return(_a0 *entity.Language, _a1 error) *MockILanguageRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockILanguageRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Language, error)) *MockILanguageRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, params
func (_m *MockILanguageRepository) List(ctx context.Context, params pagination.Params) ([]*entity.Language, *pagination.Metadata, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Language
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Params) ([]*entity.Language, *pagination.Metadata, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Params) []*entity.Language); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, pagination.Params) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockILanguageRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockILanguageRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params pagination.Params
func (_e *MockILanguageRepository_Expecter) List(ctx interface{}, params interface{}) *MockILanguageRepository_List_Call {
	return &MockILanguageRepository_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockILanguageRepository_List_Call) Run(run func(ctx context.Context, params pagination.Params)) *MockILanguageRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pagination.Params))
	})
	return _c
}

func (_c *MockILanguageRepository_List_Call) Return(_a0 []*entity.Language, _a1 *pagination.Metadata, _a2 error) *MockILanguageRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockILanguageRepository_List_Call) RunAndReturn(run func(context.Context, pagination.Params) ([]*entity.Language, *pagination.Metadata, error)) *MockILanguageRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx
func (_m *MockILanguageRepository) ListActive(ctx context.Context) ([]*entity.Language, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []*entity.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Language, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Language); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockILanguageRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockILanguageRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockILanguageRepository_Expecter) ListActive(ctx interface{}) *MockILanguageRepository_ListActive_Call {
	return &MockILanguageRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx)}
}

func (_c *MockILanguageRepository_ListActive_Call) Run(run func(ctx context.Context)) *MockILanguageRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockILanguageRepository_ListActive_Call) Return(_a0 []*entity.Language, _a1 error) *MockILanguageRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockILanguageRepository_ListActive_Call) RunAndReturn(run func(context.Context) ([]*entity.Language, error)) *MockILanguageRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, language
func (_m *MockILanguageRepository) Update(ctx context.Context, language *entity.Language) error {
	ret := _m.Called(ctx, language)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Language) error); ok {
		r0 = rf(ctx, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockILanguageRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockILanguageRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - language *entity.Language
func (_e *MockILanguageRepository_Expecter) Update(ctx interface{}, language interface{}) *MockILanguageRepository_Update_Call {
	return &MockILanguageRepository_Update_Call{Call: _e.mock.On("Update", ctx, language)}
}

func (_c *MockILanguageRepository_Update_Call) Run(run func(ctx context.Context, language *entity.Language)) *MockILanguageRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Language))
	})
	return _c
}

func (_c *MockILanguageRepository_Update_Call) Return(_a0 error) *MockILanguageRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockILanguageRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Language) error) *MockILanguageRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockILanguageRepository creates a new instance of MockILanguageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILanguageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILanguageRepository {
	mock := &MockILanguageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
