// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/basilex/promenade/pkg/pagination"

	uuid "github.com/google/uuid"
)

// MockLanguageRepository is an autogenerated mock type for the ILanguageRepository type
type MockLanguageRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, language
func (_m *MockLanguageRepository) Create(ctx context.Context, language *entity.Language) error {
	ret := _m.Called(ctx, language)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Language) error); ok {
		r0 = rf(ctx, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockLanguageRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, code
func (_m *MockLanguageRepository) Exists(ctx context.Context, code string) (bool, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *MockLanguageRepository) GetByCode(ctx context.Context, code string) (*entity.Language, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Language, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Language); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockLanguageRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Language, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Language, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Language); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, params
func (_m *MockLanguageRepository) List(ctx context.Context, params pagination.Params) ([]*entity.Language, *pagination.Metadata, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Language
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Params) ([]*entity.Language, *pagination.Metadata, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Params) []*entity.Language); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, pagination.Params) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListActive provides a mock function with given fields: ctx
func (_m *MockLanguageRepository) ListActive(ctx context.Context) ([]*entity.Language, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []*entity.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Language, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Language); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, language
func (_m *MockLanguageRepository) Update(ctx context.Context, language *entity.Language) error {
	ret := _m.Called(ctx, language)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Language) error); ok {
		r0 = rf(ctx, language)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockLanguageRepository creates a new instance of MockLanguageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLanguageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLanguageRepository {
	mock := &MockLanguageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
