// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPermissionRepository is an autogenerated mock type for the IPermissionRepository type
type MockPermissionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, permission
func (_m *MockPermissionRepository) Create(ctx context.Context, permission *entity.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMany provides a mock function with given fields: ctx, permissions
func (_m *MockPermissionRepository) CreateMany(ctx context.Context, permissions []*entity.Permission) error {
	ret := _m.Called(ctx, permissions)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entity.Permission) error); ok {
		r0 = rf(ctx, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPermissionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByResource provides a mock function with given fields: ctx, resource
func (_m *MockPermissionRepository) FindByResource(ctx context.Context, resource string) ([]*entity.Permission, error) {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for FindByResource")
	}

	var r0 []*entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Permission, error)); ok {
		return rf(ctx, resource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.Permission); ok {
		r0 = rf(ctx, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockPermissionRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDs provides a mock function with given fields: ctx, ids
func (_m *MockPermissionRepository) GetByIDs(ctx context.Context, ids []uuid.UUID) ([]*entity.Permission, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*entity.Permission, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*entity.Permission); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByResourceAction provides a mock function with given fields: ctx, resource, action
func (_m *MockPermissionRepository) GetByResourceAction(ctx context.Context, resource string, action string) (*entity.Permission, error) {
	ret := _m.Called(ctx, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for GetByResourceAction")
	}

	var r0 *entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Permission, error)); ok {
		return rf(ctx, resource, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.Permission); ok {
		r0 = rf(ctx, resource, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, resource, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *MockPermissionRepository) List(ctx context.Context) ([]*entity.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, permission
func (_m *MockPermissionRepository) Update(ctx context.Context, permission *entity.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockPermissionRepository creates a new instance of MockPermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionRepository {
	mock := &MockPermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
