// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockIPermissionRepository is an autogenerated mock type for the IPermissionRepository type
type MockIPermissionRepository struct {
	mock.Mock
}

type MockIPermissionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPermissionRepository) EXPECT() *MockIPermissionRepository_Expecter {
	return &MockIPermissionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, permission
func (_m *MockIPermissionRepository) Create(ctx context.Context, permission *entity.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPermissionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIPermissionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *entity.Permission
func (_e *MockIPermissionRepository_Expecter) Create(ctx interface{}, permission interface{}) *MockIPermissionRepository_Create_Call {
	return &MockIPermissionRepository_Create_Call{Call: _e.mock.On("Create", ctx, permission)}
}

func (_c *MockIPermissionRepository_Create_Call) Run(run func(ctx context.Context, permission *entity.Permission)) *MockIPermissionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Permission))
	})
	return _c
}

func (_c *MockIPermissionRepository_Create_Call) Return(_a0 error) *MockIPermissionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPermissionRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Permission) error) *MockIPermissionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMany provides a mock function with given fields: ctx, permissions
func (_m *MockIPermissionRepository) CreateMany(ctx context.Context, permissions []*entity.Permission) error {
	ret := _m.Called(ctx, permissions)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entity.Permission) error); ok {
		r0 = rf(ctx, permissions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPermissionRepository_CreateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMany'
type MockIPermissionRepository_CreateMany_Call struct {
	*mock.Call
}

// CreateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - permissions []*entity.Permission
func (_e *MockIPermissionRepository_Expecter) CreateMany(ctx interface{}, permissions interface{}) *MockIPermissionRepository_CreateMany_Call {
	return &MockIPermissionRepository_CreateMany_Call{Call: _e.mock.On("CreateMany", ctx, permissions)}
}

func (_c *MockIPermissionRepository_CreateMany_Call) Run(run func(ctx context.Context, permissions []*entity.Permission)) *MockIPermissionRepository_CreateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*entity.Permission))
	})
	return _c
}

func (_c *MockIPermissionRepository_CreateMany_Call) Return(_a0 error) *MockIPermissionRepository_CreateMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPermissionRepository_CreateMany_Call) RunAndReturn(run func(context.Context, []*entity.Permission) error) *MockIPermissionRepository_CreateMany_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIPermissionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPermissionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIPermissionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIPermissionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockIPermissionRepository_Delete_Call {
	return &MockIPermissionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIPermissionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIPermissionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIPermissionRepository_Delete_Call) Return(_a0 error) *MockIPermissionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPermissionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIPermissionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByResource provides a mock function with given fields: ctx, resource
func (_m *MockIPermissionRepository) FindByResource(ctx context.Context, resource string) ([]*entity.Permission, error) {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for FindByResource")
	}

	var r0 []*entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Permission, error)); ok {
		return rf(ctx, resource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entity.Permission); ok {
		r0 = rf(ctx, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPermissionRepository_FindByResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByResource'
type MockIPermissionRepository_FindByResource_Call struct {
	*mock.Call
}

// FindByResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resource string
func (_e *MockIPermissionRepository_Expecter) FindByResource(ctx interface{}, resource interface{}) *MockIPermissionRepository_FindByResource_Call {
	return &MockIPermissionRepository_FindByResource_Call{Call: _e.mock.On("FindByResource", ctx, resource)}
}

func (_c *MockIPermissionRepository_FindByResource_Call) Run(run func(ctx context.Context, resource string)) *MockIPermissionRepository_FindByResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIPermissionRepository_FindByResource_Call) Return(_a0 []*entity.Permission, _a1 error) *MockIPermissionRepository_FindByResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPermissionRepository_FindByResource_Call) RunAndReturn(run func(context.Context, string) ([]*entity.Permission, error)) *MockIPermissionRepository_FindByResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIPermissionRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Permission, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Permission, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Permission); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPermissionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIPermissionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIPermissionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIPermissionRepository_GetByID_Call {
	return &MockIPermissionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIPermissionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIPermissionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIPermissionRepository_GetByID_Call) Return(_a0 *entity.Permission, _a1 error) *MockIPermissionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPermissionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Permission, error)) *MockIPermissionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function with given fields: ctx, ids
func (_m *MockIPermissionRepository) GetByIDs(ctx context.Context, ids []uuid.UUID) ([]*entity.Permission, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*entity.Permission, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*entity.Permission); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPermissionRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockIPermissionRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockIPermissionRepository_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockIPermissionRepository_GetByIDs_Call {
	return &MockIPermissionRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockIPermissionRepository_GetByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockIPermissionRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockIPermissionRepository_GetByIDs_Call) Return(_a0 []*entity.Permission, _a1 error) *MockIPermissionRepository_GetByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPermissionRepository_GetByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*entity.Permission, error)) *MockIPermissionRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByResourceAction provides a mock function with given fields: ctx, resource, action
func (_m *MockIPermissionRepository) GetByResourceAction(ctx context.Context, resource string, action string) (*entity.Permission, error) {
	ret := _m.Called(ctx, resource, action)

	if len(ret) == 0 {
		panic("no return value specified for GetByResourceAction")
	}

	var r0 *entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Permission, error)); ok {
		return rf(ctx, resource, action)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entity.Permission); ok {
		r0 = rf(ctx, resource, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, resource, action)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPermissionRepository_GetByResourceAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByResourceAction'
type MockIPermissionRepository_GetByResourceAction_Call struct {
	*mock.Call
}

// GetByResourceAction is a helper method to define mock.On call
//   - ctx context.Context
//   - resource string
//   - action string
func (_e *MockIPermissionRepository_Expecter) GetByResourceAction(ctx interface{}, resource interface{}, action interface{}) *MockIPermissionRepository_GetByResourceAction_Call {
	return &MockIPermissionRepository_GetByResourceAction_Call{Call: _e.mock.On("GetByResourceAction", ctx, resource, action)}
}

func (_c *MockIPermissionRepository_GetByResourceAction_Call) Run(run func(ctx context.Context, resource string, action string)) *MockIPermissionRepository_GetByResourceAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIPermissionRepository_GetByResourceAction_Call) Return(_a0 *entity.Permission, _a1 error) *MockIPermissionRepository_GetByResourceAction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPermissionRepository_GetByResourceAction_Call) RunAndReturn(run func(context.Context, string, string) (*entity.Permission, error)) *MockIPermissionRepository_GetByResourceAction_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockIPermissionRepository) List(ctx context.Context) ([]*entity.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPermissionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIPermissionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPermissionRepository_Expecter) List(ctx interface{}) *MockIPermissionRepository_List_Call {
	return &MockIPermissionRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockIPermissionRepository_List_Call) Run(run func(ctx context.Context)) *MockIPermissionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIPermissionRepository_List_Call) Return(_a0 []*entity.Permission, _a1 error) *MockIPermissionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPermissionRepository_List_Call) RunAndReturn(run func(context.Context) ([]*entity.Permission, error)) *MockIPermissionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, permission
func (_m *MockIPermissionRepository) Update(ctx context.Context, permission *entity.Permission) error {
	ret := _m.Called(ctx, permission)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Permission) error); ok {
		r0 = rf(ctx, permission)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPermissionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIPermissionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - permission *entity.Permission
func (_e *MockIPermissionRepository_Expecter) Update(ctx interface{}, permission interface{}) *MockIPermissionRepository_Update_Call {
	return &MockIPermissionRepository_Update_Call{Call: _e.mock.On("Update", ctx, permission)}
}

func (_c *MockIPermissionRepository_Update_Call) Run(run func(ctx context.Context, permission *entity.Permission)) *MockIPermissionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Permission))
	})
	return _c
}

func (_c *MockIPermissionRepository_Update_Call) Return(_a0 error) *MockIPermissionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPermissionRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Permission) error) *MockIPermissionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPermissionRepository creates a new instance of MockIPermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPermissionRepository {
	mock := &MockIPermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
