// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockISessionRepository is an autogenerated mock type for the ISessionRepository type
type MockISessionRepository struct {
	mock.Mock
}

type MockISessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISessionRepository) EXPECT() *MockISessionRepository_Expecter {
	return &MockISessionRepository_Expecter{mock: &_m.Mock}
}

// CountUserSessions provides a mock function with given fields: ctx, userID
func (_m *MockISessionRepository) CountUserSessions(ctx context.Context, userID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountUserSessions")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionRepository_CountUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserSessions'
type MockISessionRepository_CountUserSessions_Call struct {
	*mock.Call
}

// CountUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockISessionRepository_Expecter) CountUserSessions(ctx interface{}, userID interface{}) *MockISessionRepository_CountUserSessions_Call {
	return &MockISessionRepository_CountUserSessions_Call{Call: _e.mock.On("CountUserSessions", ctx, userID)}
}

func (_c *MockISessionRepository_CountUserSessions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockISessionRepository_CountUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockISessionRepository_CountUserSessions_Call) Return(_a0 int, _a1 error) *MockISessionRepository_CountUserSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionRepository_CountUserSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockISessionRepository_CountUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockISessionRepository) Create(ctx context.Context, session *entity.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockISessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *entity.Session
func (_e *MockISessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockISessionRepository_Create_Call {
	return &MockISessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockISessionRepository_Create_Call) Run(run func(ctx context.Context, session *entity.Session)) *MockISessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Session))
	})
	return _c
}

func (_c *MockISessionRepository_Create_Call) Return(_a0 error) *MockISessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Session) error) *MockISessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockISessionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockISessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockISessionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockISessionRepository_Delete_Call {
	return &MockISessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockISessionRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockISessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockISessionRepository_Delete_Call) Return(_a0 error) *MockISessionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockISessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function with given fields: ctx, userID
func (_m *MockISessionRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRepository_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type MockISessionRepository_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockISessionRepository_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *MockISessionRepository_DeleteByUserID_Call {
	return &MockISessionRepository_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *MockISessionRepository_DeleteByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockISessionRepository_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockISessionRepository_DeleteByUserID_Call) Return(_a0 error) *MockISessionRepository_DeleteByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRepository_DeleteByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockISessionRepository_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx
func (_m *MockISessionRepository) DeleteExpired(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockISessionRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockISessionRepository_Expecter) DeleteExpired(ctx interface{}) *MockISessionRepository_DeleteExpired_Call {
	return &MockISessionRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *MockISessionRepository_DeleteExpired_Call) Run(run func(ctx context.Context)) *MockISessionRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockISessionRepository_DeleteExpired_Call) Return(_a0 error) *MockISessionRepository_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context) error) *MockISessionRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockISessionRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Session, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Session, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Session); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockISessionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockISessionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockISessionRepository_GetByID_Call {
	return &MockISessionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockISessionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockISessionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockISessionRepository_GetByID_Call) Return(_a0 *entity.Session, _a1 error) *MockISessionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Session, error)) *MockISessionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRefreshToken provides a mock function with given fields: ctx, hashedToken
func (_m *MockISessionRepository) GetByRefreshToken(ctx context.Context, hashedToken string) (*entity.Session, error) {
	ret := _m.Called(ctx, hashedToken)

	if len(ret) == 0 {
		panic("no return value specified for GetByRefreshToken")
	}

	var r0 *entity.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Session, error)); ok {
		return rf(ctx, hashedToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Session); ok {
		r0 = rf(ctx, hashedToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hashedToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionRepository_GetByRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRefreshToken'
type MockISessionRepository_GetByRefreshToken_Call struct {
	*mock.Call
}

// GetByRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - hashedToken string
func (_e *MockISessionRepository_Expecter) GetByRefreshToken(ctx interface{}, hashedToken interface{}) *MockISessionRepository_GetByRefreshToken_Call {
	return &MockISessionRepository_GetByRefreshToken_Call{Call: _e.mock.On("GetByRefreshToken", ctx, hashedToken)}
}

func (_c *MockISessionRepository_GetByRefreshToken_Call) Run(run func(ctx context.Context, hashedToken string)) *MockISessionRepository_GetByRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockISessionRepository_GetByRefreshToken_Call) Return(_a0 *entity.Session, _a1 error) *MockISessionRepository_GetByRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionRepository_GetByRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*entity.Session, error)) *MockISessionRepository_GetByRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetOldestSession provides a mock function with given fields: ctx, userID
func (_m *MockISessionRepository) GetOldestSession(ctx context.Context, userID uuid.UUID) (*entity.Session, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOldestSession")
	}

	var r0 *entity.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Session, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Session); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionRepository_GetOldestSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOldestSession'
type MockISessionRepository_GetOldestSession_Call struct {
	*mock.Call
}

// GetOldestSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockISessionRepository_Expecter) GetOldestSession(ctx interface{}, userID interface{}) *MockISessionRepository_GetOldestSession_Call {
	return &MockISessionRepository_GetOldestSession_Call{Call: _e.mock.On("GetOldestSession", ctx, userID)}
}

func (_c *MockISessionRepository_GetOldestSession_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockISessionRepository_GetOldestSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockISessionRepository_GetOldestSession_Call) Return(_a0 *entity.Session, _a1 error) *MockISessionRepository_GetOldestSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionRepository_GetOldestSession_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Session, error)) *MockISessionRepository_GetOldestSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSessions provides a mock function with given fields: ctx, userID
func (_m *MockISessionRepository) GetUserSessions(ctx context.Context, userID uuid.UUID) ([]*entity.Session, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSessions")
	}

	var r0 []*entity.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Session, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Session); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionRepository_GetUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSessions'
type MockISessionRepository_GetUserSessions_Call struct {
	*mock.Call
}

// GetUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockISessionRepository_Expecter) GetUserSessions(ctx interface{}, userID interface{}) *MockISessionRepository_GetUserSessions_Call {
	return &MockISessionRepository_GetUserSessions_Call{Call: _e.mock.On("GetUserSessions", ctx, userID)}
}

func (_c *MockISessionRepository_GetUserSessions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockISessionRepository_GetUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockISessionRepository_GetUserSessions_Call) Return(_a0 []*entity.Session, _a1 error) *MockISessionRepository_GetUserSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionRepository_GetUserSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*entity.Session, error)) *MockISessionRepository_GetUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, session
func (_m *MockISessionRepository) Update(ctx context.Context, session *entity.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockISessionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - session *entity.Session
func (_e *MockISessionRepository_Expecter) Update(ctx interface{}, session interface{}) *MockISessionRepository_Update_Call {
	return &MockISessionRepository_Update_Call{Call: _e.mock.On("Update", ctx, session)}
}

func (_c *MockISessionRepository_Update_Call) Run(run func(ctx context.Context, session *entity.Session)) *MockISessionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Session))
	})
	return _c
}

func (_c *MockISessionRepository_Update_Call) Return(_a0 error) *MockISessionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Session) error) *MockISessionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISessionRepository creates a new instance of MockISessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISessionRepository {
	mock := &MockISessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
