// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/basilex/promenade/pkg/pagination"

	uuid "github.com/google/uuid"
)

// MockITimezoneRepository is an autogenerated mock type for the ITimezoneRepository type
type MockITimezoneRepository struct {
	mock.Mock
}

type MockITimezoneRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITimezoneRepository) EXPECT() *MockITimezoneRepository_Expecter {
	return &MockITimezoneRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, timezone
func (_m *MockITimezoneRepository) Create(ctx context.Context, timezone *entity.Timezone) error {
	ret := _m.Called(ctx, timezone)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Timezone) error); ok {
		r0 = rf(ctx, timezone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITimezoneRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockITimezoneRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - timezone *entity.Timezone
func (_e *MockITimezoneRepository_Expecter) Create(ctx interface{}, timezone interface{}) *MockITimezoneRepository_Create_Call {
	return &MockITimezoneRepository_Create_Call{Call: _e.mock.On("Create", ctx, timezone)}
}

func (_c *MockITimezoneRepository_Create_Call) Run(run func(ctx context.Context, timezone *entity.Timezone)) *MockITimezoneRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Timezone))
	})
	return _c
}

func (_c *MockITimezoneRepository_Create_Call) Return(_a0 error) *MockITimezoneRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITimezoneRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Timezone) error) *MockITimezoneRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockITimezoneRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITimezoneRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockITimezoneRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockITimezoneRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockITimezoneRepository_Delete_Call {
	return &MockITimezoneRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockITimezoneRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockITimezoneRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockITimezoneRepository_Delete_Call) Return(_a0 error) *MockITimezoneRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITimezoneRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockITimezoneRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, name
func (_m *MockITimezoneRepository) Exists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITimezoneRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockITimezoneRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockITimezoneRepository_Expecter) Exists(ctx interface{}, name interface{}) *MockITimezoneRepository_Exists_Call {
	return &MockITimezoneRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, name)}
}

func (_c *MockITimezoneRepository_Exists_Call) Run(run func(ctx context.Context, name string)) *MockITimezoneRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockITimezoneRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockITimezoneRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITimezoneRepository_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockITimezoneRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockITimezoneRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Timezone, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Timezone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Timezone, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Timezone); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Timezone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITimezoneRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockITimezoneRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockITimezoneRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockITimezoneRepository_GetByID_Call {
	return &MockITimezoneRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockITimezoneRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockITimezoneRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockITimezoneRepository_GetByID_Call) Return(_a0 *entity.Timezone, _a1 error) *MockITimezoneRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITimezoneRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Timezone, error)) *MockITimezoneRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockITimezoneRepository) GetByName(ctx context.Context, name string) (*entity.Timezone, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *entity.Timezone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Timezone, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Timezone); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Timezone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITimezoneRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockITimezoneRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockITimezoneRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockITimezoneRepository_GetByName_Call {
	return &MockITimezoneRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockITimezoneRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockITimezoneRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockITimezoneRepository_GetByName_Call) Return(_a0 *entity.Timezone, _a1 error) *MockITimezoneRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITimezoneRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*entity.Timezone, error)) *MockITimezoneRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, params
func (_m *MockITimezoneRepository) List(ctx context.Context, params pagination.Params) ([]*entity.Timezone, *pagination.Metadata, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Timezone
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Params) ([]*entity.Timezone, *pagination.Metadata, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pagination.Params) []*entity.Timezone); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Timezone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, pagination.Params) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockITimezoneRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockITimezoneRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params pagination.Params
func (_e *MockITimezoneRepository_Expecter) List(ctx interface{}, params interface{}) *MockITimezoneRepository_List_Call {
	return &MockITimezoneRepository_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockITimezoneRepository_List_Call) Run(run func(ctx context.Context, params pagination.Params)) *MockITimezoneRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pagination.Params))
	})
	return _c
}

func (_c *MockITimezoneRepository_List_Call) Return(_a0 []*entity.Timezone, _a1 *pagination.Metadata, _a2 error) *MockITimezoneRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockITimezoneRepository_List_Call) RunAndReturn(run func(context.Context, pagination.Params) ([]*entity.Timezone, *pagination.Metadata, error)) *MockITimezoneRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListActive provides a mock function with given fields: ctx
func (_m *MockITimezoneRepository) ListActive(ctx context.Context) ([]*entity.Timezone, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListActive")
	}

	var r0 []*entity.Timezone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.Timezone, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.Timezone); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Timezone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITimezoneRepository_ListActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActive'
type MockITimezoneRepository_ListActive_Call struct {
	*mock.Call
}

// ListActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockITimezoneRepository_Expecter) ListActive(ctx interface{}) *MockITimezoneRepository_ListActive_Call {
	return &MockITimezoneRepository_ListActive_Call{Call: _e.mock.On("ListActive", ctx)}
}

func (_c *MockITimezoneRepository_ListActive_Call) Run(run func(ctx context.Context)) *MockITimezoneRepository_ListActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockITimezoneRepository_ListActive_Call) Return(_a0 []*entity.Timezone, _a1 error) *MockITimezoneRepository_ListActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITimezoneRepository_ListActive_Call) RunAndReturn(run func(context.Context) ([]*entity.Timezone, error)) *MockITimezoneRepository_ListActive_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, timezone
func (_m *MockITimezoneRepository) Update(ctx context.Context, timezone *entity.Timezone) error {
	ret := _m.Called(ctx, timezone)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Timezone) error); ok {
		r0 = rf(ctx, timezone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITimezoneRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockITimezoneRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - timezone *entity.Timezone
func (_e *MockITimezoneRepository_Expecter) Update(ctx interface{}, timezone interface{}) *MockITimezoneRepository_Update_Call {
	return &MockITimezoneRepository_Update_Call{Call: _e.mock.On("Update", ctx, timezone)}
}

func (_c *MockITimezoneRepository_Update_Call) Run(run func(ctx context.Context, timezone *entity.Timezone)) *MockITimezoneRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Timezone))
	})
	return _c
}

func (_c *MockITimezoneRepository_Update_Call) Return(_a0 error) *MockITimezoneRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITimezoneRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Timezone) error) *MockITimezoneRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITimezoneRepository creates a new instance of MockITimezoneRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITimezoneRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITimezoneRepository {
	mock := &MockITimezoneRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
