// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// Ban provides a mock function with given fields: ctx, id, reason
func (_m *MockIUserRepository) Ban(ctx context.Context, id uuid.UUID, reason string) error {
	ret := _m.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for Ban")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Ban_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ban'
type MockIUserRepository_Ban_Call struct {
	*mock.Call
}

// Ban is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reason string
func (_e *MockIUserRepository_Expecter) Ban(ctx interface{}, id interface{}, reason interface{}) *MockIUserRepository_Ban_Call {
	return &MockIUserRepository_Ban_Call{Call: _e.mock.On("Ban", ctx, id, reason)}
}

func (_c *MockIUserRepository_Ban_Call) Run(run func(ctx context.Context, id uuid.UUID, reason string)) *MockIUserRepository_Ban_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIUserRepository_Ban_Call) Return(_a0 error) *MockIUserRepository_Ban_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Ban_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockIUserRepository_Ban_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockIUserRepository) Create(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockIUserRepository_Expecter) Create(ctx interface{}, user interface{}) *MockIUserRepository_Create_Call {
	return &MockIUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockIUserRepository_Create_Call) Run(run func(ctx context.Context, user *entity.User)) *MockIUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *MockIUserRepository_Create_Call) Return(_a0 error) *MockIUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.User) error) *MockIUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Deactivate provides a mock function with given fields: ctx, id
func (_m *MockIUserRepository) Deactivate(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Deactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deactivate'
type MockIUserRepository_Deactivate_Call struct {
	*mock.Call
}

// Deactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserRepository_Expecter) Deactivate(ctx interface{}, id interface{}) *MockIUserRepository_Deactivate_Call {
	return &MockIUserRepository_Deactivate_Call{Call: _e.mock.On("Deactivate", ctx, id)}
}

func (_c *MockIUserRepository_Deactivate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserRepository_Deactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserRepository_Deactivate_Call) Return(_a0 error) *MockIUserRepository_Deactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Deactivate_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserRepository_Deactivate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIUserRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockIUserRepository_Delete_Call {
	return &MockIUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIUserRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserRepository_Delete_Call) Return(_a0 error) *MockIUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockIUserRepository) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockIUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockIUserRepository_GetByEmail_Call {
	return &MockIUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockIUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIUserRepository_GetByEmail_Call) Return(_a0 *entity.User, _a1 error) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*entity.User, error)) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIUserRepository_GetByID_Call {
	return &MockIUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIUserRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserRepository_GetByID_Call) Return(_a0 *entity.User, _a1 error) *MockIUserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.User, error)) *MockIUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MockIUserRepository) List(ctx context.Context, limit int, offset int) ([]*entity.User, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*entity.User, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*entity.User); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIUserRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockIUserRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockIUserRepository_List_Call {
	return &MockIUserRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockIUserRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockIUserRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIUserRepository_List_Call) Return(_a0 []*entity.User, _a1 error) *MockIUserRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*entity.User, error)) *MockIUserRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Reactivate provides a mock function with given fields: ctx, id
func (_m *MockIUserRepository) Reactivate(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Reactivate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Reactivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reactivate'
type MockIUserRepository_Reactivate_Call struct {
	*mock.Call
}

// Reactivate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserRepository_Expecter) Reactivate(ctx interface{}, id interface{}) *MockIUserRepository_Reactivate_Call {
	return &MockIUserRepository_Reactivate_Call{Call: _e.mock.On("Reactivate", ctx, id)}
}

func (_c *MockIUserRepository_Reactivate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserRepository_Reactivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserRepository_Reactivate_Call) Return(_a0 error) *MockIUserRepository_Reactivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Reactivate_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserRepository_Reactivate_Call {
	_c.Call.Return(run)
	return _c
}

// Suspend provides a mock function with given fields: ctx, id, reason, until
func (_m *MockIUserRepository) Suspend(ctx context.Context, id uuid.UUID, reason string, until *time.Time) error {
	ret := _m.Called(ctx, id, reason, until)

	if len(ret) == 0 {
		panic("no return value specified for Suspend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *time.Time) error); ok {
		r0 = rf(ctx, id, reason, until)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Suspend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Suspend'
type MockIUserRepository_Suspend_Call struct {
	*mock.Call
}

// Suspend is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - reason string
//   - until *time.Time
func (_e *MockIUserRepository_Expecter) Suspend(ctx interface{}, id interface{}, reason interface{}, until interface{}) *MockIUserRepository_Suspend_Call {
	return &MockIUserRepository_Suspend_Call{Call: _e.mock.On("Suspend", ctx, id, reason, until)}
}

func (_c *MockIUserRepository_Suspend_Call) Run(run func(ctx context.Context, id uuid.UUID, reason string, until *time.Time)) *MockIUserRepository_Suspend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(*time.Time))
	})
	return _c
}

func (_c *MockIUserRepository_Suspend_Call) Return(_a0 error) *MockIUserRepository_Suspend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Suspend_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, *time.Time) error) *MockIUserRepository_Suspend_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockIUserRepository) Update(ctx context.Context, user *entity.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockIUserRepository_Expecter) Update(ctx interface{}, user interface{}) *MockIUserRepository_Update_Call {
	return &MockIUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockIUserRepository_Update_Call) Run(run func(ctx context.Context, user *entity.User)) *MockIUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User))
	})
	return _c
}

func (_c *MockIUserRepository_Update_Call) Return(_a0 error) *MockIUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.User) error) *MockIUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastLogin provides a mock function with given fields: ctx, id, loginTime
func (_m *MockIUserRepository) UpdateLastLogin(ctx context.Context, id uuid.UUID, loginTime time.Time) error {
	ret := _m.Called(ctx, id, loginTime)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, loginTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_UpdateLastLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastLogin'
type MockIUserRepository_UpdateLastLogin_Call struct {
	*mock.Call
}

// UpdateLastLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - loginTime time.Time
func (_e *MockIUserRepository_Expecter) UpdateLastLogin(ctx interface{}, id interface{}, loginTime interface{}) *MockIUserRepository_UpdateLastLogin_Call {
	return &MockIUserRepository_UpdateLastLogin_Call{Call: _e.mock.On("UpdateLastLogin", ctx, id, loginTime)}
}

func (_c *MockIUserRepository_UpdateLastLogin_Call) Run(run func(ctx context.Context, id uuid.UUID, loginTime time.Time)) *MockIUserRepository_UpdateLastLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockIUserRepository_UpdateLastLogin_Call) Return(_a0 error) *MockIUserRepository_UpdateLastLogin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_UpdateLastLogin_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockIUserRepository_UpdateLastLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, id, hashedPassword
func (_m *MockIUserRepository) UpdatePassword(ctx context.Context, id uuid.UUID, hashedPassword string) error {
	ret := _m.Called(ctx, id, hashedPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, hashedPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockIUserRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - hashedPassword string
func (_e *MockIUserRepository_Expecter) UpdatePassword(ctx interface{}, id interface{}, hashedPassword interface{}) *MockIUserRepository_UpdatePassword_Call {
	return &MockIUserRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, id, hashedPassword)}
}

func (_c *MockIUserRepository_UpdatePassword_Call) Run(run func(ctx context.Context, id uuid.UUID, hashedPassword string)) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIUserRepository_UpdatePassword_Call) Return(_a0 error) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockIUserRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status entity.UserStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.UserStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIUserRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status entity.UserStatus
func (_e *MockIUserRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockIUserRepository_UpdateStatus_Call {
	return &MockIUserRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockIUserRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status entity.UserStatus)) *MockIUserRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.UserStatus))
	})
	return _c
}

func (_c *MockIUserRepository_UpdateStatus_Call) Return(_a0 error) *MockIUserRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.UserStatus) error) *MockIUserRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, id
func (_m *MockIUserRepository) VerifyEmail(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserRepository_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockIUserRepository_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserRepository_Expecter) VerifyEmail(ctx interface{}, id interface{}) *MockIUserRepository_VerifyEmail_Call {
	return &MockIUserRepository_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, id)}
}

func (_c *MockIUserRepository_VerifyEmail_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserRepository_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserRepository_VerifyEmail_Call) Return(_a0 error) *MockIUserRepository_VerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserRepository_VerifyEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserRepository_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
