// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/modules/posts/domain/entity"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/basilex/promenade/pkg/pagination"

	uuid "github.com/google/uuid"
)

// MockICommentRepository is an autogenerated mock type for the ICommentRepository type
type MockICommentRepository struct {
	mock.Mock
}

type MockICommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICommentRepository) EXPECT() *MockICommentRepository_Expecter {
	return &MockICommentRepository_Expecter{mock: &_m.Mock}
}

// CountPostComments provides a mock function with given fields: ctx, postID
func (_m *MockICommentRepository) CountPostComments(ctx context.Context, postID uuid.UUID) (int, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for CountPostComments")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, postID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICommentRepository_CountPostComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPostComments'
type MockICommentRepository_CountPostComments_Call struct {
	*mock.Call
}

// CountPostComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uuid.UUID
func (_e *MockICommentRepository_Expecter) CountPostComments(ctx interface{}, postID interface{}) *MockICommentRepository_CountPostComments_Call {
	return &MockICommentRepository_CountPostComments_Call{Call: _e.mock.On("CountPostComments", ctx, postID)}
}

func (_c *MockICommentRepository_CountPostComments_Call) Run(run func(ctx context.Context, postID uuid.UUID)) *MockICommentRepository_CountPostComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICommentRepository_CountPostComments_Call) Return(_a0 int, _a1 error) *MockICommentRepository_CountPostComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICommentRepository_CountPostComments_Call) RunAndReturn(run func(context.Context, uuid.UUID) (int, error)) *MockICommentRepository_CountPostComments_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, comment
func (_m *MockICommentRepository) Create(ctx context.Context, comment *entity.Comment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Comment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *entity.Comment
func (_e *MockICommentRepository_Expecter) Create(ctx interface{}, comment interface{}) *MockICommentRepository_Create_Call {
	return &MockICommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, comment)}
}

func (_c *MockICommentRepository_Create_Call) Run(run func(ctx context.Context, comment *entity.Comment)) *MockICommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Comment))
	})
	return _c
}

func (_c *MockICommentRepository_Create_Call) Return(_a0 error) *MockICommentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICommentRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.Comment) error) *MockICommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementRepliesCount provides a mock function with given fields: ctx, parentID
func (_m *MockICommentRepository) DecrementRepliesCount(ctx context.Context, parentID uuid.UUID) error {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for DecrementRepliesCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, parentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICommentRepository_DecrementRepliesCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementRepliesCount'
type MockICommentRepository_DecrementRepliesCount_Call struct {
	*mock.Call
}

// DecrementRepliesCount is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID uuid.UUID
func (_e *MockICommentRepository_Expecter) DecrementRepliesCount(ctx interface{}, parentID interface{}) *MockICommentRepository_DecrementRepliesCount_Call {
	return &MockICommentRepository_DecrementRepliesCount_Call{Call: _e.mock.On("DecrementRepliesCount", ctx, parentID)}
}

func (_c *MockICommentRepository_DecrementRepliesCount_Call) Run(run func(ctx context.Context, parentID uuid.UUID)) *MockICommentRepository_DecrementRepliesCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICommentRepository_DecrementRepliesCount_Call) Return(_a0 error) *MockICommentRepository_DecrementRepliesCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICommentRepository_DecrementRepliesCount_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockICommentRepository_DecrementRepliesCount_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockICommentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICommentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICommentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockICommentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockICommentRepository_Delete_Call {
	return &MockICommentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockICommentRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockICommentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICommentRepository_Delete_Call) Return(_a0 error) *MockICommentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICommentRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockICommentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockICommentRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICommentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockICommentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockICommentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockICommentRepository_GetByID_Call {
	return &MockICommentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockICommentRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockICommentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICommentRepository_GetByID_Call) Return(_a0 *entity.Comment, _a1 error) *MockICommentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICommentRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.Comment, error)) *MockICommentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostComments provides a mock function with given fields: ctx, postID, limit, offset
func (_m *MockICommentRepository) GetPostComments(ctx context.Context, postID uuid.UUID, limit int, offset int) ([]*entity.Comment, *pagination.Metadata, error) {
	ret := _m.Called(ctx, postID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPostComments")
	}

	var r0 []*entity.Comment
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Comment, *pagination.Metadata, error)); ok {
		return rf(ctx, postID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Comment); ok {
		r0 = rf(ctx, postID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) *pagination.Metadata); ok {
		r1 = rf(ctx, postID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, postID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICommentRepository_GetPostComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostComments'
type MockICommentRepository_GetPostComments_Call struct {
	*mock.Call
}

// GetPostComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockICommentRepository_Expecter) GetPostComments(ctx interface{}, postID interface{}, limit interface{}, offset interface{}) *MockICommentRepository_GetPostComments_Call {
	return &MockICommentRepository_GetPostComments_Call{Call: _e.mock.On("GetPostComments", ctx, postID, limit, offset)}
}

func (_c *MockICommentRepository_GetPostComments_Call) Run(run func(ctx context.Context, postID uuid.UUID, limit int, offset int)) *MockICommentRepository_GetPostComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockICommentRepository_GetPostComments_Call) Return(_a0 []*entity.Comment, _a1 *pagination.Metadata, _a2 error) *MockICommentRepository_GetPostComments_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICommentRepository_GetPostComments_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Comment, *pagination.Metadata, error)) *MockICommentRepository_GetPostComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplies provides a mock function with given fields: ctx, parentID, limit, offset
func (_m *MockICommentRepository) GetReplies(ctx context.Context, parentID uuid.UUID, limit int, offset int) ([]*entity.Comment, *pagination.Metadata, error) {
	ret := _m.Called(ctx, parentID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetReplies")
	}

	var r0 []*entity.Comment
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Comment, *pagination.Metadata, error)); ok {
		return rf(ctx, parentID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Comment); ok {
		r0 = rf(ctx, parentID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) *pagination.Metadata); ok {
		r1 = rf(ctx, parentID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, parentID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICommentRepository_GetReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplies'
type MockICommentRepository_GetReplies_Call struct {
	*mock.Call
}

// GetReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockICommentRepository_Expecter) GetReplies(ctx interface{}, parentID interface{}, limit interface{}, offset interface{}) *MockICommentRepository_GetReplies_Call {
	return &MockICommentRepository_GetReplies_Call{Call: _e.mock.On("GetReplies", ctx, parentID, limit, offset)}
}

func (_c *MockICommentRepository_GetReplies_Call) Run(run func(ctx context.Context, parentID uuid.UUID, limit int, offset int)) *MockICommentRepository_GetReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockICommentRepository_GetReplies_Call) Return(_a0 []*entity.Comment, _a1 *pagination.Metadata, _a2 error) *MockICommentRepository_GetReplies_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICommentRepository_GetReplies_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Comment, *pagination.Metadata, error)) *MockICommentRepository_GetReplies_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserComments provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockICommentRepository) GetUserComments(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*entity.Comment, *pagination.Metadata, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserComments")
	}

	var r0 []*entity.Comment
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.Comment, *pagination.Metadata, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.Comment); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) *pagination.Metadata); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockICommentRepository_GetUserComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserComments'
type MockICommentRepository_GetUserComments_Call struct {
	*mock.Call
}

// GetUserComments is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockICommentRepository_Expecter) GetUserComments(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockICommentRepository_GetUserComments_Call {
	return &MockICommentRepository_GetUserComments_Call{Call: _e.mock.On("GetUserComments", ctx, userID, limit, offset)}
}

func (_c *MockICommentRepository_GetUserComments_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockICommentRepository_GetUserComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockICommentRepository_GetUserComments_Call) Return(_a0 []*entity.Comment, _a1 *pagination.Metadata, _a2 error) *MockICommentRepository_GetUserComments_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockICommentRepository_GetUserComments_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.Comment, *pagination.Metadata, error)) *MockICommentRepository_GetUserComments_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementRepliesCount provides a mock function with given fields: ctx, parentID
func (_m *MockICommentRepository) IncrementRepliesCount(ctx context.Context, parentID uuid.UUID) error {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementRepliesCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, parentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICommentRepository_IncrementRepliesCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementRepliesCount'
type MockICommentRepository_IncrementRepliesCount_Call struct {
	*mock.Call
}

// IncrementRepliesCount is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID uuid.UUID
func (_e *MockICommentRepository_Expecter) IncrementRepliesCount(ctx interface{}, parentID interface{}) *MockICommentRepository_IncrementRepliesCount_Call {
	return &MockICommentRepository_IncrementRepliesCount_Call{Call: _e.mock.On("IncrementRepliesCount", ctx, parentID)}
}

func (_c *MockICommentRepository_IncrementRepliesCount_Call) Run(run func(ctx context.Context, parentID uuid.UUID)) *MockICommentRepository_IncrementRepliesCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockICommentRepository_IncrementRepliesCount_Call) Return(_a0 error) *MockICommentRepository_IncrementRepliesCount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICommentRepository_IncrementRepliesCount_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockICommentRepository_IncrementRepliesCount_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, comment
func (_m *MockICommentRepository) Update(ctx context.Context, comment *entity.Comment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Comment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICommentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICommentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *entity.Comment
func (_e *MockICommentRepository_Expecter) Update(ctx interface{}, comment interface{}) *MockICommentRepository_Update_Call {
	return &MockICommentRepository_Update_Call{Call: _e.mock.On("Update", ctx, comment)}
}

func (_c *MockICommentRepository_Update_Call) Run(run func(ctx context.Context, comment *entity.Comment)) *MockICommentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Comment))
	})
	return _c
}

func (_c *MockICommentRepository_Update_Call) Return(_a0 error) *MockICommentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICommentRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.Comment) error) *MockICommentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICommentRepository creates a new instance of MockICommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICommentRepository {
	mock := &MockICommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
