// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/modules/posts/domain/entity"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/basilex/promenade/pkg/pagination"

	repository "github.com/basilex/promenade/internal/modules/posts/domain/repository"

	uuid "github.com/google/uuid"
)

// MockIUserPostRepository is an autogenerated mock type for the IUserPostRepository type
type MockIUserPostRepository struct {
	mock.Mock
}

type MockIUserPostRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserPostRepository) EXPECT() *MockIUserPostRepository_Expecter {
	return &MockIUserPostRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, post
func (_m *MockIUserPostRepository) Create(ctx context.Context, post *entity.UserPost) error {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserPost) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserPostRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - post *entity.UserPost
func (_e *MockIUserPostRepository_Expecter) Create(ctx interface{}, post interface{}) *MockIUserPostRepository_Create_Call {
	return &MockIUserPostRepository_Create_Call{Call: _e.mock.On("Create", ctx, post)}
}

func (_c *MockIUserPostRepository_Create_Call) Run(run func(ctx context.Context, post *entity.UserPost)) *MockIUserPostRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserPost))
	})
	return _c
}

func (_c *MockIUserPostRepository_Create_Call) Return(_a0 error) *MockIUserPostRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.UserPost) error) *MockIUserPostRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementComments provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) DecrementComments(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DecrementComments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_DecrementComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementComments'
type MockIUserPostRepository_DecrementComments_Call struct {
	*mock.Call
}

// DecrementComments is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) DecrementComments(ctx interface{}, id interface{}) *MockIUserPostRepository_DecrementComments_Call {
	return &MockIUserPostRepository_DecrementComments_Call{Call: _e.mock.On("DecrementComments", ctx, id)}
}

func (_c *MockIUserPostRepository_DecrementComments_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_DecrementComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_DecrementComments_Call) Return(_a0 error) *MockIUserPostRepository_DecrementComments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_DecrementComments_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_DecrementComments_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementLikes provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) DecrementLikes(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DecrementLikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_DecrementLikes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementLikes'
type MockIUserPostRepository_DecrementLikes_Call struct {
	*mock.Call
}

// DecrementLikes is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) DecrementLikes(ctx interface{}, id interface{}) *MockIUserPostRepository_DecrementLikes_Call {
	return &MockIUserPostRepository_DecrementLikes_Call{Call: _e.mock.On("DecrementLikes", ctx, id)}
}

func (_c *MockIUserPostRepository_DecrementLikes_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_DecrementLikes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_DecrementLikes_Call) Return(_a0 error) *MockIUserPostRepository_DecrementLikes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_DecrementLikes_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_DecrementLikes_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIUserPostRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockIUserPostRepository_Delete_Call {
	return &MockIUserPostRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIUserPostRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_Delete_Call) Return(_a0 error) *MockIUserPostRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.UserPost, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.UserPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.UserPost, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.UserPost); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserPostRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIUserPostRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIUserPostRepository_GetByID_Call {
	return &MockIUserPostRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIUserPostRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_GetByID_Call) Return(_a0 *entity.UserPost, _a1 error) *MockIUserPostRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserPostRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.UserPost, error)) *MockIUserPostRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function with given fields: ctx, userID, slug
func (_m *MockIUserPostRepository) GetBySlug(ctx context.Context, userID uuid.UUID, slug string) (*entity.UserPost, error) {
	ret := _m.Called(ctx, userID, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *entity.UserPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entity.UserPost, error)); ok {
		return rf(ctx, userID, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entity.UserPost); ok {
		r0 = rf(ctx, userID, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserPostRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockIUserPostRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - slug string
func (_e *MockIUserPostRepository_Expecter) GetBySlug(ctx interface{}, userID interface{}, slug interface{}) *MockIUserPostRepository_GetBySlug_Call {
	return &MockIUserPostRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, userID, slug)}
}

func (_c *MockIUserPostRepository_GetBySlug_Call) Run(run func(ctx context.Context, userID uuid.UUID, slug string)) *MockIUserPostRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIUserPostRepository_GetBySlug_Call) Return(_a0 *entity.UserPost, _a1 error) *MockIUserPostRepository_GetBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserPostRepository_GetBySlug_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*entity.UserPost, error)) *MockIUserPostRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTag provides a mock function with given fields: ctx, tag, limit, offset
func (_m *MockIUserPostRepository) GetByTag(ctx context.Context, tag string, limit int, offset int) ([]*entity.UserPost, error) {
	ret := _m.Called(ctx, tag, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByTag")
	}

	var r0 []*entity.UserPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.UserPost, error)); ok {
		return rf(ctx, tag, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.UserPost); ok {
		r0 = rf(ctx, tag, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, tag, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserPostRepository_GetByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTag'
type MockIUserPostRepository_GetByTag_Call struct {
	*mock.Call
}

// GetByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
//   - limit int
//   - offset int
func (_e *MockIUserPostRepository_Expecter) GetByTag(ctx interface{}, tag interface{}, limit interface{}, offset interface{}) *MockIUserPostRepository_GetByTag_Call {
	return &MockIUserPostRepository_GetByTag_Call{Call: _e.mock.On("GetByTag", ctx, tag, limit, offset)}
}

func (_c *MockIUserPostRepository_GetByTag_Call) Run(run func(ctx context.Context, tag string, limit int, offset int)) *MockIUserPostRepository_GetByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIUserPostRepository_GetByTag_Call) Return(_a0 []*entity.UserPost, _a1 error) *MockIUserPostRepository_GetByTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserPostRepository_GetByTag_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*entity.UserPost, error)) *MockIUserPostRepository_GetByTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeaturedPosts provides a mock function with given fields: ctx, limit
func (_m *MockIUserPostRepository) GetFeaturedPosts(ctx context.Context, limit int) ([]*entity.UserPost, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetFeaturedPosts")
	}

	var r0 []*entity.UserPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*entity.UserPost, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*entity.UserPost); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserPostRepository_GetFeaturedPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeaturedPosts'
type MockIUserPostRepository_GetFeaturedPosts_Call struct {
	*mock.Call
}

// GetFeaturedPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockIUserPostRepository_Expecter) GetFeaturedPosts(ctx interface{}, limit interface{}) *MockIUserPostRepository_GetFeaturedPosts_Call {
	return &MockIUserPostRepository_GetFeaturedPosts_Call{Call: _e.mock.On("GetFeaturedPosts", ctx, limit)}
}

func (_c *MockIUserPostRepository_GetFeaturedPosts_Call) Run(run func(ctx context.Context, limit int)) *MockIUserPostRepository_GetFeaturedPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIUserPostRepository_GetFeaturedPosts_Call) Return(_a0 []*entity.UserPost, _a1 error) *MockIUserPostRepository_GetFeaturedPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserPostRepository_GetFeaturedPosts_Call) RunAndReturn(run func(context.Context, int) ([]*entity.UserPost, error)) *MockIUserPostRepository_GetFeaturedPosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublishedPosts provides a mock function with given fields: ctx, limit, offset
func (_m *MockIUserPostRepository) GetPublishedPosts(ctx context.Context, limit int, offset int) ([]*entity.UserPost, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPublishedPosts")
	}

	var r0 []*entity.UserPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*entity.UserPost, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*entity.UserPost); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserPostRepository_GetPublishedPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublishedPosts'
type MockIUserPostRepository_GetPublishedPosts_Call struct {
	*mock.Call
}

// GetPublishedPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockIUserPostRepository_Expecter) GetPublishedPosts(ctx interface{}, limit interface{}, offset interface{}) *MockIUserPostRepository_GetPublishedPosts_Call {
	return &MockIUserPostRepository_GetPublishedPosts_Call{Call: _e.mock.On("GetPublishedPosts", ctx, limit, offset)}
}

func (_c *MockIUserPostRepository_GetPublishedPosts_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockIUserPostRepository_GetPublishedPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIUserPostRepository_GetPublishedPosts_Call) Return(_a0 []*entity.UserPost, _a1 error) *MockIUserPostRepository_GetPublishedPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserPostRepository_GetPublishedPosts_Call) RunAndReturn(run func(context.Context, int, int) ([]*entity.UserPost, error)) *MockIUserPostRepository_GetPublishedPosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetScheduledPosts provides a mock function with given fields: ctx
func (_m *MockIUserPostRepository) GetScheduledPosts(ctx context.Context) ([]*entity.UserPost, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetScheduledPosts")
	}

	var r0 []*entity.UserPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entity.UserPost, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entity.UserPost); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserPostRepository_GetScheduledPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduledPosts'
type MockIUserPostRepository_GetScheduledPosts_Call struct {
	*mock.Call
}

// GetScheduledPosts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIUserPostRepository_Expecter) GetScheduledPosts(ctx interface{}) *MockIUserPostRepository_GetScheduledPosts_Call {
	return &MockIUserPostRepository_GetScheduledPosts_Call{Call: _e.mock.On("GetScheduledPosts", ctx)}
}

func (_c *MockIUserPostRepository_GetScheduledPosts_Call) Run(run func(ctx context.Context)) *MockIUserPostRepository_GetScheduledPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIUserPostRepository_GetScheduledPosts_Call) Return(_a0 []*entity.UserPost, _a1 error) *MockIUserPostRepository_GetScheduledPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserPostRepository_GetScheduledPosts_Call) RunAndReturn(run func(context.Context) ([]*entity.UserPost, error)) *MockIUserPostRepository_GetScheduledPosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPosts provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockIUserPostRepository) GetUserPosts(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]*entity.UserPost, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPosts")
	}

	var r0 []*entity.UserPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*entity.UserPost, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*entity.UserPost); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserPostRepository_GetUserPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPosts'
type MockIUserPostRepository_GetUserPosts_Call struct {
	*mock.Call
}

// GetUserPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockIUserPostRepository_Expecter) GetUserPosts(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockIUserPostRepository_GetUserPosts_Call {
	return &MockIUserPostRepository_GetUserPosts_Call{Call: _e.mock.On("GetUserPosts", ctx, userID, limit, offset)}
}

func (_c *MockIUserPostRepository_GetUserPosts_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockIUserPostRepository_GetUserPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIUserPostRepository_GetUserPosts_Call) Return(_a0 []*entity.UserPost, _a1 error) *MockIUserPostRepository_GetUserPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserPostRepository_GetUserPosts_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*entity.UserPost, error)) *MockIUserPostRepository_GetUserPosts_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementComments provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) IncrementComments(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementComments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_IncrementComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementComments'
type MockIUserPostRepository_IncrementComments_Call struct {
	*mock.Call
}

// IncrementComments is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) IncrementComments(ctx interface{}, id interface{}) *MockIUserPostRepository_IncrementComments_Call {
	return &MockIUserPostRepository_IncrementComments_Call{Call: _e.mock.On("IncrementComments", ctx, id)}
}

func (_c *MockIUserPostRepository_IncrementComments_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_IncrementComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_IncrementComments_Call) Return(_a0 error) *MockIUserPostRepository_IncrementComments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_IncrementComments_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_IncrementComments_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementLikes provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) IncrementLikes(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementLikes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_IncrementLikes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementLikes'
type MockIUserPostRepository_IncrementLikes_Call struct {
	*mock.Call
}

// IncrementLikes is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) IncrementLikes(ctx interface{}, id interface{}) *MockIUserPostRepository_IncrementLikes_Call {
	return &MockIUserPostRepository_IncrementLikes_Call{Call: _e.mock.On("IncrementLikes", ctx, id)}
}

func (_c *MockIUserPostRepository_IncrementLikes_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_IncrementLikes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_IncrementLikes_Call) Return(_a0 error) *MockIUserPostRepository_IncrementLikes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_IncrementLikes_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_IncrementLikes_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementShares provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) IncrementShares(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementShares")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_IncrementShares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementShares'
type MockIUserPostRepository_IncrementShares_Call struct {
	*mock.Call
}

// IncrementShares is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) IncrementShares(ctx interface{}, id interface{}) *MockIUserPostRepository_IncrementShares_Call {
	return &MockIUserPostRepository_IncrementShares_Call{Call: _e.mock.On("IncrementShares", ctx, id)}
}

func (_c *MockIUserPostRepository_IncrementShares_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_IncrementShares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_IncrementShares_Call) Return(_a0 error) *MockIUserPostRepository_IncrementShares_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_IncrementShares_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_IncrementShares_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementViews provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) IncrementViews(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementViews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_IncrementViews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementViews'
type MockIUserPostRepository_IncrementViews_Call struct {
	*mock.Call
}

// IncrementViews is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) IncrementViews(ctx interface{}, id interface{}) *MockIUserPostRepository_IncrementViews_Call {
	return &MockIUserPostRepository_IncrementViews_Call{Call: _e.mock.On("IncrementViews", ctx, id)}
}

func (_c *MockIUserPostRepository_IncrementViews_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_IncrementViews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_IncrementViews_Call) Return(_a0 error) *MockIUserPostRepository_IncrementViews_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_IncrementViews_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_IncrementViews_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, params
func (_m *MockIUserPostRepository) List(ctx context.Context, params repository.ListPostsParams) ([]*entity.UserPost, *pagination.Metadata, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.UserPost
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListPostsParams) ([]*entity.UserPost, *pagination.Metadata, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ListPostsParams) []*entity.UserPost); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ListPostsParams) *pagination.Metadata); ok {
		r1 = rf(ctx, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ListPostsParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIUserPostRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIUserPostRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.ListPostsParams
func (_e *MockIUserPostRepository_Expecter) List(ctx interface{}, params interface{}) *MockIUserPostRepository_List_Call {
	return &MockIUserPostRepository_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockIUserPostRepository_List_Call) Run(run func(ctx context.Context, params repository.ListPostsParams)) *MockIUserPostRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ListPostsParams))
	})
	return _c
}

func (_c *MockIUserPostRepository_List_Call) Return(_a0 []*entity.UserPost, _a1 *pagination.Metadata, _a2 error) *MockIUserPostRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIUserPostRepository_List_Call) RunAndReturn(run func(context.Context, repository.ListPostsParams) ([]*entity.UserPost, *pagination.Metadata, error)) *MockIUserPostRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// PublishScheduledPost provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) PublishScheduledPost(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for PublishScheduledPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_PublishScheduledPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishScheduledPost'
type MockIUserPostRepository_PublishScheduledPost_Call struct {
	*mock.Call
}

// PublishScheduledPost is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) PublishScheduledPost(ctx interface{}, id interface{}) *MockIUserPostRepository_PublishScheduledPost_Call {
	return &MockIUserPostRepository_PublishScheduledPost_Call{Call: _e.mock.On("PublishScheduledPost", ctx, id)}
}

func (_c *MockIUserPostRepository_PublishScheduledPost_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_PublishScheduledPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_PublishScheduledPost_Call) Return(_a0 error) *MockIUserPostRepository_PublishScheduledPost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_PublishScheduledPost_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_PublishScheduledPost_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) Restore(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockIUserPostRepository_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) Restore(ctx interface{}, id interface{}) *MockIUserPostRepository_Restore_Call {
	return &MockIUserPostRepository_Restore_Call{Call: _e.mock.On("Restore", ctx, id)}
}

func (_c *MockIUserPostRepository_Restore_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_Restore_Call) Return(_a0 error) *MockIUserPostRepository_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_Restore_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, query, limit, offset
func (_m *MockIUserPostRepository) Search(ctx context.Context, query string, limit int, offset int) ([]*entity.UserPost, error) {
	ret := _m.Called(ctx, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*entity.UserPost
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*entity.UserPost, error)); ok {
		return rf(ctx, query, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*entity.UserPost); ok {
		r0 = rf(ctx, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.UserPost)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIUserPostRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockIUserPostRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
//   - offset int
func (_e *MockIUserPostRepository_Expecter) Search(ctx interface{}, query interface{}, limit interface{}, offset interface{}) *MockIUserPostRepository_Search_Call {
	return &MockIUserPostRepository_Search_Call{Call: _e.mock.On("Search", ctx, query, limit, offset)}
}

func (_c *MockIUserPostRepository_Search_Call) Run(run func(ctx context.Context, query string, limit int, offset int)) *MockIUserPostRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockIUserPostRepository_Search_Call) Return(_a0 []*entity.UserPost, _a1 error) *MockIUserPostRepository_Search_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIUserPostRepository_Search_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*entity.UserPost, error)) *MockIUserPostRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *MockIUserPostRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockIUserPostRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserPostRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockIUserPostRepository_SoftDelete_Call {
	return &MockIUserPostRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockIUserPostRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserPostRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIUserPostRepository_SoftDelete_Call) Return(_a0 error) *MockIUserPostRepository_SoftDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_SoftDelete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockIUserPostRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, post
func (_m *MockIUserPostRepository) Update(ctx context.Context, post *entity.UserPost) error {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserPost) error); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserPostRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - post *entity.UserPost
func (_e *MockIUserPostRepository_Expecter) Update(ctx interface{}, post interface{}) *MockIUserPostRepository_Update_Call {
	return &MockIUserPostRepository_Update_Call{Call: _e.mock.On("Update", ctx, post)}
}

func (_c *MockIUserPostRepository_Update_Call) Run(run func(ctx context.Context, post *entity.UserPost)) *MockIUserPostRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserPost))
	})
	return _c
}

func (_c *MockIUserPostRepository_Update_Call) Return(_a0 error) *MockIUserPostRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_Update_Call) RunAndReturn(run func(context.Context, *entity.UserPost) error) *MockIUserPostRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockIUserPostRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status entity.PostStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.PostStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIUserPostRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockIUserPostRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status entity.PostStatus
func (_e *MockIUserPostRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockIUserPostRepository_UpdateStatus_Call {
	return &MockIUserPostRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockIUserPostRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status entity.PostStatus)) *MockIUserPostRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.PostStatus))
	})
	return _c
}

func (_c *MockIUserPostRepository_UpdateStatus_Call) Return(_a0 error) *MockIUserPostRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIUserPostRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, entity.PostStatus) error) *MockIUserPostRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserPostRepository creates a new instance of MockIUserPostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserPostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserPostRepository {
	mock := &MockIUserPostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
