package reference

































































}	return c.Code == other.Codefunc (c Country) Equals(other Country) bool {// Equals checks if two countries are the same (by ISO code).}	return c.Namefunc (c Country) String() string {// String returns the country name.}	}, nil		IsActive:  true,		PhoneCode: phoneCode,		Name:      name,		Code:      code,		ID:        uuidv7.New(),	return Country{	}		phoneCode = "+" + phoneCode	if !strings.HasPrefix(phoneCode, "+") {	// Phone code must start with +	}		return Country{}, fmt.Errorf("phone code is required")	if phoneCode == "" {	}		return Country{}, fmt.Errorf("country name is required")	if name == "" {	}		return Country{}, fmt.Errorf("country code must be 2 characters (ISO 3166-1 alpha-2)")	if len(code) != 2 {	phoneCode = strings.TrimSpace(phoneCode)	name = strings.TrimSpace(name)	code = strings.ToUpper(strings.TrimSpace(code))func NewCountry(code, name, phoneCode string) (Country, error) {// NewCountry creates a new Country value object with validation.}	IsActive    bool        // Whether country is active in system	PhoneCode   string      // Phone country code (+1, +380, +49, etc.)	NameLocal   string      // Local name (optional)	Name        string      // English name	NumericCode string      // ISO 3166-1 numeric (840, 804, 276, etc.)	Code3       string      // ISO 3166-1 alpha-3 (USA, UKR, DEU, etc.)	Code        string      // ISO 3166-1 alpha-2 (US, UA, DE, etc.)	ID          uuidv7.UUID // Unique identifiertype Country struct {// This is a Value Object shared across all contexts.// Country represents an ISO 3166-1 country.)	"github.com/basilex/promenade/pkg/uuidv7"	"strings"	"fmt"import (package reference// accessible by all Bounded Contexts. This is part of the Shared Kernel.// Package reference provides shared reference data (countries, currencies, languages, timezones)