package reference
package reference















































































}	return fmt.Sprintf(format, c.Symbol, whole, fraction)	format := fmt.Sprintf("%%s%%d.%%0%dd", c.DecimalPlaces)	fraction := amount % divisor	whole := amount / divisor	}		divisor *= 10	for i := 0; i < c.DecimalPlaces; i++ {	divisor := int64(1)	}		return fmt.Sprintf("%s%d", c.Symbol, amount)	if c.DecimalPlaces == 0 {func (c Currency) FormatAmount(amount int64) string {// FormatAmount formats a monetary amount with proper decimal places.}	return c.Code == other.Codefunc (c Currency) Equals(other Currency) bool {// Equals checks if two currencies are the same (by ISO code).}	return c.Codefunc (c Currency) String() string {// String returns the currency code.}	}, nil		IsActive:      true,		DecimalPlaces: decimalPlaces,		Symbol:        symbol,		Name:          name,		Code:          code,		ID:            uuidv7.New(),	return Currency{	}		return Currency{}, fmt.Errorf("decimal places must be between 0 and 4")	if decimalPlaces < 0 || decimalPlaces > 4 {	}		return Currency{}, fmt.Errorf("currency symbol is required")	if symbol == "" {	}		return Currency{}, fmt.Errorf("currency name is required")	if name == "" {	}		return Currency{}, fmt.Errorf("currency code must be 3 characters (ISO 4217)")	if len(code) != 3 {	symbol = strings.TrimSpace(symbol)	name = strings.TrimSpace(name)	code = strings.ToUpper(strings.TrimSpace(code))func NewCurrency(code, name, symbol string, decimalPlaces int) (Currency, error) {// NewCurrency creates a new Currency value object with validation.}	IsActive     bool        // Whether currency is active in system	DecimalPlaces int        // Number of decimal places (2 for USD, 0 for JPY, etc.)	Symbol       string      // Currency symbol ($, €, ₴, etc.)	Name         string      // English name	NumericCode  string      // ISO 4217 numeric code (840, 978, 980, etc.)	Code         string      // ISO 4217 alpha code (USD, EUR, UAH, etc.)	ID           uuidv7.UUID // Unique identifiertype Currency struct {// This is a Value Object shared across all contexts.// Currency represents an ISO 4217 currency.)	"github.com/basilex/promenade/pkg/uuidv7"	"strings"	"fmt"import (