package reference
package reference

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/jmoiron/sqlx"






















































































































































































































}	return timezones, nil	}		return nil, fmt.Errorf("failed to list timezones: %w", err)	if err != nil {	err := r.db.SelectContext(ctx, &timezones, query)			  FROM shared_timezones WHERE is_active = true ORDER BY name`	query := `SELECT id, name, abbreviation, utc_offset, is_active 	var timezones []Timezonefunc (r *Repository) ListTimezones(ctx context.Context) ([]Timezone, error) {// ListTimezones retrieves all active timezones.}	return &timezone, nil	}		return nil, fmt.Errorf("failed to get timezone: %w", err)	if err != nil {	}		return nil, fmt.Errorf("timezone not found")	if err == sql.ErrNoRows {	err := r.db.GetContext(ctx, &timezone, query, name)			  FROM shared_timezones WHERE name = $1 AND is_active = true`	query := `SELECT id, name, abbreviation, utc_offset, is_active 	var timezone Timezonefunc (r *Repository) GetTimezoneByName(ctx context.Context, name string) (*Timezone, error) {// GetTimezoneByName retrieves a timezone by IANA name.}	return &timezone, nil	}		return nil, fmt.Errorf("failed to get timezone: %w", err)	if err != nil {	}		return nil, fmt.Errorf("timezone not found")	if err == sql.ErrNoRows {	err := r.db.GetContext(ctx, &timezone, query, id)			  FROM shared_timezones WHERE id = $1 AND is_active = true`	query := `SELECT id, name, abbreviation, utc_offset, is_active 	var timezone Timezonefunc (r *Repository) GetTimezoneByID(ctx context.Context, id uuidv7.UUID) (*Timezone, error) {// GetTimezoneByID retrieves a timezone by ID.// Timezones}	return languages, nil	}		return nil, fmt.Errorf("failed to list languages: %w", err)	if err != nil {	err := r.db.SelectContext(ctx, &languages, query)			  FROM shared_languages WHERE is_active = true ORDER BY name`	query := `SELECT id, code, code3, name, native_name, is_active 	var languages []Languagefunc (r *Repository) ListLanguages(ctx context.Context) ([]Language, error) {// ListLanguages retrieves all active languages.}	return &language, nil	}		return nil, fmt.Errorf("failed to get language: %w", err)	if err != nil {	}		return nil, fmt.Errorf("language not found")	if err == sql.ErrNoRows {	err := r.db.GetContext(ctx, &language, query, code)			  FROM shared_languages WHERE code = $1 AND is_active = true`	query := `SELECT id, code, code3, name, native_name, is_active 	var language Languagefunc (r *Repository) GetLanguageByCode(ctx context.Context, code string) (*Language, error) {// GetLanguageByCode retrieves a language by ISO code.}	return &language, nil	}		return nil, fmt.Errorf("failed to get language: %w", err)	if err != nil {	}		return nil, fmt.Errorf("language not found")	if err == sql.ErrNoRows {	err := r.db.GetContext(ctx, &language, query, id)			  FROM shared_languages WHERE id = $1 AND is_active = true`	query := `SELECT id, code, code3, name, native_name, is_active 	var language Languagefunc (r *Repository) GetLanguageByID(ctx context.Context, id uuidv7.UUID) (*Language, error) {// GetLanguageByID retrieves a language by ID.// Languages}	return currencies, nil	}		return nil, fmt.Errorf("failed to list currencies: %w", err)	if err != nil {	err := r.db.SelectContext(ctx, &currencies, query)			  FROM shared_currencies WHERE is_active = true ORDER BY code`	query := `SELECT id, code, numeric_code, name, symbol, decimal_places, is_active 	var currencies []Currencyfunc (r *Repository) ListCurrencies(ctx context.Context) ([]Currency, error) {// ListCurrencies retrieves all active currencies.}	return &currency, nil	}		return nil, fmt.Errorf("failed to get currency: %w", err)	if err != nil {	}		return nil, fmt.Errorf("currency not found")	if err == sql.ErrNoRows {	err := r.db.GetContext(ctx, &currency, query, code)			  FROM shared_currencies WHERE code = $1 AND is_active = true`	query := `SELECT id, code, numeric_code, name, symbol, decimal_places, is_active 	var currency Currencyfunc (r *Repository) GetCurrencyByCode(ctx context.Context, code string) (*Currency, error) {// GetCurrencyByCode retrieves a currency by ISO code.}	return &currency, nil	}		return nil, fmt.Errorf("failed to get currency: %w", err)	if err != nil {	}		return nil, fmt.Errorf("currency not found")	if err == sql.ErrNoRows {	err := r.db.GetContext(ctx, &currency, query, id)			  FROM shared_currencies WHERE id = $1 AND is_active = true`	query := `SELECT id, code, numeric_code, name, symbol, decimal_places, is_active 	var currency Currencyfunc (r *Repository) GetCurrencyByID(ctx context.Context, id uuidv7.UUID) (*Currency, error) {// GetCurrencyByID retrieves a currency by ID.// Currencies}	return countries, nil	}		return nil, fmt.Errorf("failed to list countries: %w", err)	if err != nil {	err := r.db.SelectContext(ctx, &countries, query)			  FROM shared_countries WHERE is_active = true ORDER BY name`	query := `SELECT id, code, code3, numeric_code, name, name_local, phone_code, is_active 	var countries []Countryfunc (r *Repository) ListCountries(ctx context.Context) ([]Country, error) {// ListCountries retrieves all active countries.}	return &country, nil	}		return nil, fmt.Errorf("failed to get country: %w", err)	if err != nil {	}		return nil, fmt.Errorf("country not found")	if err == sql.ErrNoRows {	err := r.db.GetContext(ctx, &country, query, code)			  FROM shared_countries WHERE code = $1 AND is_active = true`	query := `SELECT id, code, code3, numeric_code, name, name_local, phone_code, is_active 	var country Countryfunc (r *Repository) GetCountryByCode(ctx context.Context, code string) (*Country, error) {// GetCountryByCode retrieves a country by ISO code.}	return &country, nil	}		return nil, fmt.Errorf("failed to get country: %w", err)	if err != nil {	}		return nil, fmt.Errorf("country not found")	if err == sql.ErrNoRows {	err := r.db.GetContext(ctx, &country, query, id)			  FROM shared_countries WHERE id = $1 AND is_active = true`	query := `SELECT id, code, code3, numeric_code, name, name_local, phone_code, is_active 	var country Countryfunc (r *Repository) GetCountryByID(ctx context.Context, id uuidv7.UUID) (*Country, error) {// GetCountryByID retrieves a country by ID.// Countries}	return &Repository{db: db}func NewRepository(db *sqlx.DB) *Repository {// NewRepository creates a new reference repository.}	db *sqlx.DBtype Repository struct {// This is intentionally read-only - reference data is managed via migrations.// Repository provides read-only access to reference data.)	"github.com/basilex/promenade/pkg/uuidv7"