package shared

import (
	"context"
	"log/slog"

	"github.com/basilex/promenade/internal/contexts/shared/country"
	"github.com/basilex/promenade/pkg/logger"
	"github.com/basilex/promenade/pkg/ref"
	"github.com/basilex/promenade/pkg/uuidv7"
)

// CountriesData returns reference country data for seeding (30 countries with full metadata)
func CountriesData() []*country.Country {

	return []*country.Country{
		// North America
		{
			ID:           uuidv7.New(),
			Code:         "US",
			Code3:        "USA",
			NumericCode:  "840",
			Name:         "United States",
			NameLocal:    "United States",
			PhoneCode:    "+1",
			Capital:      "Washington, D.C.",
			Region:       "Americas",
			Subregion:    "Northern America",
			FlagEmoji:    "🇺🇸",
			Latitude:     ref.Float64(38.8951),
			Longitude:    ref.To(-77.0364),
			AreaKm2:      ref.Int(9833520),
			Population:   ref.Int64(331002651),
			Translations: map[string]any{"uk": "Сполучені Штати", "de": "Vereinigte Staaten", "fr": "États-Unis"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "CA",
			Code3:        "CAN",
			NumericCode:  "124",
			Name:         "Canada",
			NameLocal:    "Canada",
			PhoneCode:    "+1",
			Capital:      "Ottawa",
			Region:       "Americas",
			Subregion:    "Northern America",
			FlagEmoji:    "🇨🇦",
			Latitude:     ref.Float64(45.4215),
			Longitude:    ref.To(-75.6972),
			AreaKm2:      ref.Int(9984670),
			Population:   ref.Int64(37742154),
			Translations: map[string]any{"uk": "Канада", "de": "Kanada", "fr": "Canada"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "MX",
			Code3:        "MEX",
			NumericCode:  "484",
			Name:         "Mexico",
			NameLocal:    "México",
			PhoneCode:    "+52",
			Capital:      "Mexico City",
			Region:       "Americas",
			Subregion:    "Central America",
			FlagEmoji:    "🇲🇽",
			Latitude:     ref.Float64(19.4326),
			Longitude:    ref.To(-99.1332),
			AreaKm2:      ref.Int(1964375),
			Population:   ref.Int64(128932753),
			Translations: map[string]any{"uk": "Мексика", "de": "Mexiko", "fr": "Mexique"},
			IsActive:     true,
		},

		// Western Europe
		{
			ID:           uuidv7.New(),
			Code:         "GB",
			Code3:        "GBR",
			NumericCode:  "826",
			Name:         "United Kingdom",
			NameLocal:    "United Kingdom",
			PhoneCode:    "+44",
			Capital:      "London",
			Region:       "Europe",
			Subregion:    "Northern Europe",
			FlagEmoji:    "🇬🇧",
			Latitude:     ref.Float64(51.5074),
			Longitude:    ref.To(-0.1278),
			AreaKm2:      ref.Int(242495),
			Population:   ref.Int64(67886011),
			Translations: map[string]any{"uk": "Велика Британія", "de": "Vereinigtes Königreich", "fr": "Royaume-Uni"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "DE",
			Code3:        "DEU",
			NumericCode:  "276",
			Name:         "Germany",
			NameLocal:    "Deutschland",
			PhoneCode:    "+49",
			Capital:      "Berlin",
			Region:       "Europe",
			Subregion:    "Western Europe",
			FlagEmoji:    "🇩🇪",
			Latitude:     ref.Float64(52.5200),
			Longitude:    ref.Float64(13.4050),
			AreaKm2:      ref.Int(357114),
			Population:   ref.Int64(83783942),
			Translations: map[string]any{"uk": "Німеччина", "de": "Deutschland", "fr": "Allemagne"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "FR",
			Code3:        "FRA",
			NumericCode:  "250",
			Name:         "France",
			NameLocal:    "France",
			PhoneCode:    "+33",
			Capital:      "Paris",
			Region:       "Europe",
			Subregion:    "Western Europe",
			FlagEmoji:    "🇫🇷",
			Latitude:     ref.Float64(48.8566),
			Longitude:    ref.Float64(2.3522),
			AreaKm2:      ref.Int(551695),
			Population:   ref.Int64(65273511),
			Translations: map[string]any{"uk": "Франція", "de": "Frankreich", "fr": "France"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "ES",
			Code3:        "ESP",
			NumericCode:  "724",
			Name:         "Spain",
			NameLocal:    "España",
			PhoneCode:    "+34",
			Capital:      "Madrid",
			Region:       "Europe",
			Subregion:    "Southern Europe",
			FlagEmoji:    "🇪🇸",
			Latitude:     ref.Float64(40.4168),
			Longitude:    ref.To(-3.7038),
			AreaKm2:      ref.Int(505992),
			Population:   ref.Int64(46754778),
			Translations: map[string]any{"uk": "Іспанія", "de": "Spanien", "fr": "Espagne"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "IT",
			Code3:        "ITA",
			NumericCode:  "380",
			Name:         "Italy",
			NameLocal:    "Italia",
			PhoneCode:    "+39",
			Capital:      "Rome",
			Region:       "Europe",
			Subregion:    "Southern Europe",
			FlagEmoji:    "🇮🇹",
			Latitude:     ref.Float64(41.9028),
			Longitude:    ref.Float64(12.4964),
			AreaKm2:      ref.Int(301340),
			Population:   ref.Int64(60461826),
			Translations: map[string]any{"uk": "Італія", "de": "Italien", "fr": "Italie"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "NL",
			Code3:        "NLD",
			NumericCode:  "528",
			Name:         "Netherlands",
			NameLocal:    "Nederland",
			PhoneCode:    "+31",
			Capital:      "Amsterdam",
			Region:       "Europe",
			Subregion:    "Western Europe",
			FlagEmoji:    "🇳🇱",
			Latitude:     ref.Float64(52.3676),
			Longitude:    ref.Float64(4.9041),
			AreaKm2:      ref.Int(41543),
			Population:   ref.Int64(17134872),
			Translations: map[string]any{"uk": "Нідерланди", "de": "Niederlande", "fr": "Pays-Bas"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "BE",
			Code3:        "BEL",
			NumericCode:  "056",
			Name:         "Belgium",
			NameLocal:    "België",
			PhoneCode:    "+32",
			Capital:      "Brussels",
			Region:       "Europe",
			Subregion:    "Western Europe",
			FlagEmoji:    "🇧🇪",
			Latitude:     ref.Float64(50.8503),
			Longitude:    ref.Float64(4.3517),
			AreaKm2:      ref.Int(30528),
			Population:   ref.Int64(11589623),
			Translations: map[string]any{"uk": "Бельгія", "de": "Belgien", "fr": "Belgique"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "CH",
			Code3:        "CHE",
			NumericCode:  "756",
			Name:         "Switzerland",
			NameLocal:    "Schweiz",
			PhoneCode:    "+41",
			Capital:      "Bern",
			Region:       "Europe",
			Subregion:    "Western Europe",
			FlagEmoji:    "🇨🇭",
			Latitude:     ref.Float64(46.9480),
			Longitude:    ref.Float64(7.4474),
			AreaKm2:      ref.Int(41290),
			Population:   ref.Int64(8654622),
			Translations: map[string]any{"uk": "Швейцарія", "de": "Schweiz", "fr": "Suisse"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "AT",
			Code3:        "AUT",
			NumericCode:  "040",
			Name:         "Austria",
			NameLocal:    "Österreich",
			PhoneCode:    "+43",
			Capital:      "Vienna",
			Region:       "Europe",
			Subregion:    "Western Europe",
			FlagEmoji:    "🇦🇹",
			Latitude:     ref.Float64(48.2082),
			Longitude:    ref.Float64(16.3738),
			AreaKm2:      ref.Int(83871),
			Population:   ref.Int64(9006398),
			Translations: map[string]any{"uk": "Австрія", "de": "Österreich", "fr": "Autriche"},
			IsActive:     true,
		},

		// Northern Europe
		{
			ID:           uuidv7.New(),
			Code:         "SE",
			Code3:        "SWE",
			NumericCode:  "752",
			Name:         "Sweden",
			NameLocal:    "Sverige",
			PhoneCode:    "+46",
			Capital:      "Stockholm",
			Region:       "Europe",
			Subregion:    "Northern Europe",
			FlagEmoji:    "🇸🇪",
			Latitude:     ref.Float64(59.3293),
			Longitude:    ref.Float64(18.0686),
			AreaKm2:      ref.Int(450295),
			Population:   ref.Int64(10099265),
			Translations: map[string]any{"uk": "Швеція", "de": "Schweden", "fr": "Suède"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "NO",
			Code3:        "NOR",
			NumericCode:  "578",
			Name:         "Norway",
			NameLocal:    "Norge",
			PhoneCode:    "+47",
			Capital:      "Oslo",
			Region:       "Europe",
			Subregion:    "Northern Europe",
			FlagEmoji:    "🇳🇴",
			Latitude:     ref.Float64(59.9139),
			Longitude:    ref.Float64(10.7522),
			AreaKm2:      ref.Int(323802),
			Population:   ref.Int64(5421241),
			Translations: map[string]any{"uk": "Норвегія", "de": "Norwegen", "fr": "Norvège"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "DK",
			Code3:        "DNK",
			NumericCode:  "208",
			Name:         "Denmark",
			NameLocal:    "Danmark",
			PhoneCode:    "+45",
			Capital:      "Copenhagen",
			Region:       "Europe",
			Subregion:    "Northern Europe",
			FlagEmoji:    "🇩🇰",
			Latitude:     ref.Float64(55.6761),
			Longitude:    ref.Float64(12.5683),
			AreaKm2:      ref.Int(43094),
			Population:   ref.Int64(5792202),
			Translations: map[string]any{"uk": "Данія", "de": "Dänemark", "fr": "Danemark"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "FI",
			Code3:        "FIN",
			NumericCode:  "246",
			Name:         "Finland",
			NameLocal:    "Suomi",
			PhoneCode:    "+358",
			Capital:      "Helsinki",
			Region:       "Europe",
			Subregion:    "Northern Europe",
			FlagEmoji:    "🇫🇮",
			Latitude:     ref.Float64(60.1699),
			Longitude:    ref.Float64(24.9384),
			AreaKm2:      ref.Int(338424),
			Population:   ref.Int64(5540720),
			Translations: map[string]any{"uk": "Фінляндія", "de": "Finnland", "fr": "Finlande"},
			IsActive:     true,
		},

		// Eastern Europe
		{
			ID:           uuidv7.New(),
			Code:         "UA",
			Code3:        "UKR",
			NumericCode:  "804",
			Name:         "Ukraine",
			NameLocal:    "Україна",
			PhoneCode:    "+380",
			Capital:      "Kyiv",
			Region:       "Europe",
			Subregion:    "Eastern Europe",
			FlagEmoji:    "🇺🇦",
			Latitude:     ref.Float64(50.4501),
			Longitude:    ref.Float64(30.5234),
			AreaKm2:      ref.Int(603500),
			Population:   ref.Int64(43733762),
			Translations: map[string]any{"en": "Ukraine", "de": "Ukraine", "fr": "Ukraine"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "PL",
			Code3:        "POL",
			NumericCode:  "616",
			Name:         "Poland",
			NameLocal:    "Polska",
			PhoneCode:    "+48",
			Capital:      "Warsaw",
			Region:       "Europe",
			Subregion:    "Eastern Europe",
			FlagEmoji:    "🇵🇱",
			Latitude:     ref.Float64(52.2297),
			Longitude:    ref.Float64(21.0122),
			AreaKm2:      ref.Int(312696),
			Population:   ref.Int64(37846611),
			Translations: map[string]any{"uk": "Польща", "de": "Polen", "fr": "Pologne"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "CZ",
			Code3:        "CZE",
			NumericCode:  "203",
			Name:         "Czech Republic",
			NameLocal:    "Česko",
			PhoneCode:    "+420",
			Capital:      "Prague",
			Region:       "Europe",
			Subregion:    "Eastern Europe",
			FlagEmoji:    "🇨🇿",
			Latitude:     ref.Float64(50.0755),
			Longitude:    ref.Float64(14.4378),
			AreaKm2:      ref.Int(78865),
			Population:   ref.Int64(10708981),
			Translations: map[string]any{"uk": "Чехія", "de": "Tschechien", "fr": "République tchèque"},
			IsActive:     true,
		},

		// Asia
		{
			ID:           uuidv7.New(),
			Code:         "JP",
			Code3:        "JPN",
			NumericCode:  "392",
			Name:         "Japan",
			NameLocal:    "日本",
			PhoneCode:    "+81",
			Capital:      "Tokyo",
			Region:       "Asia",
			Subregion:    "Eastern Asia",
			FlagEmoji:    "🇯🇵",
			Latitude:     ref.Float64(35.6762),
			Longitude:    ref.Float64(139.6503),
			AreaKm2:      ref.Int(377930),
			Population:   ref.Int64(126476461),
			Translations: map[string]any{"uk": "Японія", "de": "Japan", "fr": "Japon"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "CN",
			Code3:        "CHN",
			NumericCode:  "156",
			Name:         "China",
			NameLocal:    "中国",
			PhoneCode:    "+86",
			Capital:      "Beijing",
			Region:       "Asia",
			Subregion:    "Eastern Asia",
			FlagEmoji:    "🇨🇳",
			Latitude:     ref.Float64(39.9042),
			Longitude:    ref.Float64(116.4074),
			AreaKm2:      ref.Int(9596961),
			Population:   ref.Int64(1439323776),
			Translations: map[string]any{"uk": "Китай", "de": "China", "fr": "Chine"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "IN",
			Code3:        "IND",
			NumericCode:  "356",
			Name:         "India",
			NameLocal:    "भारत",
			PhoneCode:    "+91",
			Capital:      "New Delhi",
			Region:       "Asia",
			Subregion:    "Southern Asia",
			FlagEmoji:    "🇮🇳",
			Latitude:     ref.Float64(28.6139),
			Longitude:    ref.Float64(77.2090),
			AreaKm2:      ref.Int(3287590),
			Population:   ref.Int64(1380004385),
			Translations: map[string]any{"uk": "Індія", "de": "Indien", "fr": "Inde"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "KR",
			Code3:        "KOR",
			NumericCode:  "410",
			Name:         "South Korea",
			NameLocal:    "대한민국",
			PhoneCode:    "+82",
			Capital:      "Seoul",
			Region:       "Asia",
			Subregion:    "Eastern Asia",
			FlagEmoji:    "🇰🇷",
			Latitude:     ref.Float64(37.5665),
			Longitude:    ref.Float64(126.9780),
			AreaKm2:      ref.Int(100210),
			Population:   ref.Int64(51269185),
			Translations: map[string]any{"uk": "Південна Корея", "de": "Südkorea", "fr": "Corée du Sud"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "SG",
			Code3:        "SGP",
			NumericCode:  "702",
			Name:         "Singapore",
			NameLocal:    "Singapore",
			PhoneCode:    "+65",
			Capital:      "Singapore",
			Region:       "Asia",
			Subregion:    "South-Eastern Asia",
			FlagEmoji:    "🇸🇬",
			Latitude:     ref.Float64(1.3521),
			Longitude:    ref.Float64(103.8198),
			AreaKm2:      ref.Int(719),
			Population:   ref.Int64(5850342),
			Translations: map[string]any{"uk": "Сінгапур", "de": "Singapur", "fr": "Singapour"},
			IsActive:     true,
		},

		// Oceania
		{
			ID:           uuidv7.New(),
			Code:         "AU",
			Code3:        "AUS",
			NumericCode:  "036",
			Name:         "Australia",
			NameLocal:    "Australia",
			PhoneCode:    "+61",
			Capital:      "Canberra",
			Region:       "Oceania",
			Subregion:    "Australia and New Zealand",
			FlagEmoji:    "🇦🇺",
			Latitude:     ref.To(-35.2809),
			Longitude:    ref.Float64(149.1300),
			AreaKm2:      ref.Int(7692024),
			Population:   ref.Int64(25499884),
			Translations: map[string]any{"uk": "Австралія", "de": "Australien", "fr": "Australie"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "NZ",
			Code3:        "NZL",
			NumericCode:  "554",
			Name:         "New Zealand",
			NameLocal:    "New Zealand",
			PhoneCode:    "+64",
			Capital:      "Wellington",
			Region:       "Oceania",
			Subregion:    "Australia and New Zealand",
			FlagEmoji:    "🇳🇿",
			Latitude:     ref.To(-41.2865),
			Longitude:    ref.Float64(174.7762),
			AreaKm2:      ref.Int(270467),
			Population:   ref.Int64(4822233),
			Translations: map[string]any{"uk": "Нова Зеландія", "de": "Neuseeland", "fr": "Nouvelle-Zélande"},
			IsActive:     true,
		},

		// South America
		{
			ID:           uuidv7.New(),
			Code:         "BR",
			Code3:        "BRA",
			NumericCode:  "076",
			Name:         "Brazil",
			NameLocal:    "Brasil",
			PhoneCode:    "+55",
			Capital:      "Brasília",
			Region:       "Americas",
			Subregion:    "South America",
			FlagEmoji:    "🇧🇷",
			Latitude:     ref.To(-15.8267),
			Longitude:    ref.To(-47.9218),
			AreaKm2:      ref.Int(8515767),
			Population:   ref.Int64(212559417),
			Translations: map[string]any{"uk": "Бразилія", "de": "Brasilien", "fr": "Brésil"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "AR",
			Code3:        "ARG",
			NumericCode:  "032",
			Name:         "Argentina",
			NameLocal:    "Argentina",
			PhoneCode:    "+54",
			Capital:      "Buenos Aires",
			Region:       "Americas",
			Subregion:    "South America",
			FlagEmoji:    "🇦🇷",
			Latitude:     ref.To(-34.6037),
			Longitude:    ref.To(-58.3816),
			AreaKm2:      ref.Int(2780400),
			Population:   ref.Int64(45195774),
			Translations: map[string]any{"uk": "Аргентина", "de": "Argentinien", "fr": "Argentine"},
			IsActive:     true,
		},

		// Middle East
		{
			ID:           uuidv7.New(),
			Code:         "AE",
			Code3:        "ARE",
			NumericCode:  "784",
			Name:         "United Arab Emirates",
			NameLocal:    "الإمارات العربية المتحدة",
			PhoneCode:    "+971",
			Capital:      "Abu Dhabi",
			Region:       "Asia",
			Subregion:    "Western Asia",
			FlagEmoji:    "🇦🇪",
			Latitude:     ref.Float64(24.4539),
			Longitude:    ref.Float64(54.3773),
			AreaKm2:      ref.Int(83600),
			Population:   ref.Int64(9890402),
			Translations: map[string]any{"uk": "Об'єднані Арабські Емірати", "de": "Vereinigte Arabische Emirate", "fr": "Émirats arabes unis"},
			IsActive:     true,
		},
		{
			ID:           uuidv7.New(),
			Code:         "IL",
			Code3:        "ISR",
			NumericCode:  "376",
			Name:         "Israel",
			NameLocal:    "ישראל",
			PhoneCode:    "+972",
			Capital:      "Jerusalem",
			Region:       "Asia",
			Subregion:    "Western Asia",
			FlagEmoji:    "🇮🇱",
			Latitude:     ref.Float64(31.7683),
			Longitude:    ref.Float64(35.2137),
			AreaKm2:      ref.Int(20770),
			Population:   ref.Int64(8655535),
			Translations: map[string]any{"uk": "Ізраїль", "de": "Israel", "fr": "Israël"},
			IsActive:     true,
		},

		// Africa
		{
			ID:           uuidv7.New(),
			Code:         "ZA",
			Code3:        "ZAF",
			NumericCode:  "710",
			Name:         "South Africa",
			NameLocal:    "South Africa",
			PhoneCode:    "+27",
			Capital:      "Pretoria",
			Region:       "Africa",
			Subregion:    "Southern Africa",
			FlagEmoji:    "🇿🇦",
			Latitude:     ref.To(-25.7479),
			Longitude:    ref.Float64(28.2293),
			AreaKm2:      ref.Int(1221037),
			Population:   ref.Int64(59308690),
		Translations: map[string]any{"uk": "Південна Африка", "de": "Südafrika", "fr": "Afrique du Sud"},
		IsActive:     true,
	},
	}
}

// SeedCountries inserts country data into database
func SeedCountries(ctx context.Context, repo country.IRepository) error {
	countries := CountriesData()
	logger.FromContext(ctx).Info("Seeding countries...", slog.Int("count", len(countries)))

	for _, c := range countries {
		if err := repo.Create(ctx, c); err != nil {
			return err
		}
	}

	logger.FromContext(ctx).Info("Countries seeded successfully", slog.Int("count", len(countries)))
	return nil
}
