// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/basilex/promenade/internal/modules/profiles/entity"
	"github.com/basilex/promenade/pkg/uuidv7"
	"github.com/stretchr/testify/mock"
)

// MockIUserContactRepository is a mock implementation of IUserContactRepository interface
type MockIUserContactRepository struct {
	mock.Mock
}

// Create mocks the Create method
func (m *MockIUserContactRepository) Create(ctx context.Context, contact *entity.UserContact) error {
	args := m.Called(ctx, contact)
	return args.Error(0)
}

// GetByID mocks the GetByID method
func (m *MockIUserContactRepository) GetByID(ctx context.Context, id uuidv7.UUID) (*entity.UserContact, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.UserContact), args.Error(1)
}

// GetUserContacts mocks the GetUserContacts method
func (m *MockIUserContactRepository) GetUserContacts(ctx context.Context, userID uuidv7.UUID, includeInactive bool) ([]*entity.UserContact, error) {
	args := m.Called(ctx, userID, includeInactive)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.UserContact), args.Error(1)
}

// GetUserContactsByType mocks the GetUserContactsByType method
func (m *MockIUserContactRepository) GetUserContactsByType(ctx context.Context, userID uuidv7.UUID, contactType entity.ContactType) ([]*entity.UserContact, error) {
	args := m.Called(ctx, userID, contactType)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.UserContact), args.Error(1)
}

// GetPrimaryContact mocks the GetPrimaryContact method
func (m *MockIUserContactRepository) GetPrimaryContact(ctx context.Context, userID uuidv7.UUID, contactType entity.ContactType) (*entity.UserContact, error) {
	args := m.Called(ctx, userID, contactType)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.UserContact), args.Error(1)
}

// GetPublicContacts mocks the GetPublicContacts method
func (m *MockIUserContactRepository) GetPublicContacts(ctx context.Context, userID uuidv7.UUID) ([]*entity.UserContact, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.UserContact), args.Error(1)
}

// Update mocks the Update method
func (m *MockIUserContactRepository) Update(ctx context.Context, contact *entity.UserContact) error {
	args := m.Called(ctx, contact)
	return args.Error(0)
}

// Delete mocks the Delete method
func (m *MockIUserContactRepository) Delete(ctx context.Context, id uuidv7.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// SetPrimary mocks the SetPrimary method
func (m *MockIUserContactRepository) SetPrimary(ctx context.Context, userID uuidv7.UUID, contactType entity.ContactType, id uuidv7.UUID) error {
	args := m.Called(ctx, userID, contactType, id)
	return args.Error(0)
}

// VerifyContact mocks the VerifyContact method
func (m *MockIUserContactRepository) VerifyContact(ctx context.Context, id uuidv7.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}
