// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/basilex/promenade/internal/modules/profiles/entity"
	"github.com/basilex/promenade/pkg/uuidv7"
	"github.com/stretchr/testify/mock"
)

// MockIUserProfileRepository is a mock implementation of IUserProfileRepository interface
type MockIUserProfileRepository struct {
	mock.Mock
}

// Create mocks the Create method
func (m *MockIUserProfileRepository) Create(ctx context.Context, profile *entity.UserProfile) error {
	args := m.Called(ctx, profile)
	return args.Error(0)
}

// GetByID mocks the GetByID method
func (m *MockIUserProfileRepository) GetByID(ctx context.Context, id uuidv7.UUID) (*entity.UserProfile, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.UserProfile), args.Error(1)
}

// GetByUserID mocks the GetByUserID method
func (m *MockIUserProfileRepository) GetByUserID(ctx context.Context, userID uuidv7.UUID) (*entity.UserProfile, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.UserProfile), args.Error(1)
}

// GetByNickname mocks the GetByNickname method
func (m *MockIUserProfileRepository) GetByNickname(ctx context.Context, nickname string) (*entity.UserProfile, error) {
	args := m.Called(ctx, nickname)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.UserProfile), args.Error(1)
}

// Update mocks the Update method
func (m *MockIUserProfileRepository) Update(ctx context.Context, profile *entity.UserProfile) error {
	args := m.Called(ctx, profile)
	return args.Error(0)
}

// Delete mocks the Delete method
func (m *MockIUserProfileRepository) Delete(ctx context.Context, id uuidv7.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// List mocks the List method
func (m *MockIUserProfileRepository) List(ctx context.Context, limit, offset int, isPublic *bool) ([]*entity.UserProfile, error) {
	args := m.Called(ctx, limit, offset, isPublic)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.UserProfile), args.Error(1)
}

// UpdateLastSeen mocks the UpdateLastSeen method
func (m *MockIUserProfileRepository) UpdateLastSeen(ctx context.Context, profileID uuidv7.UUID) error {
	args := m.Called(ctx, profileID)
	return args.Error(0)
}

// IncrementProfileViews mocks the IncrementProfileViews method
func (m *MockIUserProfileRepository) IncrementProfileViews(ctx context.Context, profileID uuidv7.UUID) error {
	args := m.Called(ctx, profileID)
	return args.Error(0)
}

// Ban mocks the Ban method
func (m *MockIUserProfileRepository) Ban(ctx context.Context, profileID uuidv7.UUID, reason string, bannedBy uuidv7.UUID) error {
	args := m.Called(ctx, profileID, reason, bannedBy)
	return args.Error(0)
}

// Unban mocks the Unban method
func (m *MockIUserProfileRepository) Unban(ctx context.Context, profileID uuidv7.UUID) error {
	args := m.Called(ctx, profileID)
	return args.Error(0)
}

// SetVerified mocks the SetVerified method
func (m *MockIUserProfileRepository) SetVerified(ctx context.Context, profileID uuidv7.UUID, verified bool) error {
	args := m.Called(ctx, profileID, verified)
	return args.Error(0)
}

// Search mocks the Search method
func (m *MockIUserProfileRepository) Search(ctx context.Context, query string, limit, offset int) ([]*entity.UserProfile, error) {
	args := m.Called(ctx, query, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.UserProfile), args.Error(1)
}
