// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/basilex/promenade/internal/modules/billing/domain/entity"
	"github.com/basilex/promenade/pkg/uuidv7"
	"github.com/stretchr/testify/mock"
)

// MockIInvoiceRepository is a mock of IInvoiceRepository interface
type MockIInvoiceRepository struct {
	mock.Mock
}

// Create mocks the Create method
func (m *MockIInvoiceRepository) Create(ctx context.Context, invoice *entity.Invoice) error {
	args := m.Called(ctx, invoice)
	return args.Error(0)
}

// GetByID mocks the GetByID method
func (m *MockIInvoiceRepository) GetByID(ctx context.Context, id uuidv7.UUID) (*entity.Invoice, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.Invoice), args.Error(1)
}

// GetByInvoiceNumber mocks the GetByInvoiceNumber method
func (m *MockIInvoiceRepository) GetByInvoiceNumber(ctx context.Context, invoiceNumber string) (*entity.Invoice, error) {
	args := m.Called(ctx, invoiceNumber)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.Invoice), args.Error(1)
}

// GetBySubscriptionID mocks the GetBySubscriptionID method
func (m *MockIInvoiceRepository) GetBySubscriptionID(ctx context.Context, subscriptionID uuidv7.UUID) ([]*entity.Invoice, error) {
	args := m.Called(ctx, subscriptionID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Invoice), args.Error(1)
}

// GetByUserID mocks the GetByUserID method
func (m *MockIInvoiceRepository) GetByUserID(ctx context.Context, userID uuidv7.UUID, limit, offset int) ([]*entity.Invoice, error) {
	args := m.Called(ctx, userID, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Invoice), args.Error(1)
}

// GetOverdue mocks the GetOverdue method
func (m *MockIInvoiceRepository) GetOverdue(ctx context.Context, limit int) ([]*entity.Invoice, error) {
	args := m.Called(ctx, limit)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Invoice), args.Error(1)
}

// List mocks the List method
func (m *MockIInvoiceRepository) List(ctx context.Context, status *entity.InvoiceStatus, limit, offset int) ([]*entity.Invoice, error) {
	args := m.Called(ctx, status, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Invoice), args.Error(1)
}

// Count mocks the Count method
func (m *MockIInvoiceRepository) Count(ctx context.Context, status *entity.InvoiceStatus) (int, error) {
	args := m.Called(ctx, status)
	return args.Int(0), args.Error(1)
}

// Update mocks the Update method
func (m *MockIInvoiceRepository) Update(ctx context.Context, invoice *entity.Invoice) error {
	args := m.Called(ctx, invoice)
	return args.Error(0)
}

// Delete mocks the Delete method
func (m *MockIInvoiceRepository) Delete(ctx context.Context, id uuidv7.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// NewMockIInvoiceRepository creates a new mock instance
func NewMockIInvoiceRepository() *MockIInvoiceRepository {
	return &MockIInvoiceRepository{}
}
