// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/basilex/promenade/internal/modules/billing/domain/entity"
	"github.com/basilex/promenade/pkg/uuidv7"
	"github.com/stretchr/testify/mock"
)

// MockIPaymentRepository is a mock of IPaymentRepository interface
type MockIPaymentRepository struct {
	mock.Mock
}

// Create mocks the Create method
func (m *MockIPaymentRepository) Create(ctx context.Context, payment *entity.Payment) error {
	args := m.Called(ctx, payment)
	return args.Error(0)
}

// GetByID mocks the GetByID method
func (m *MockIPaymentRepository) GetByID(ctx context.Context, id uuidv7.UUID) (*entity.Payment, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.Payment), args.Error(1)
}

// GetByTransactionID mocks the GetByTransactionID method
func (m *MockIPaymentRepository) GetByTransactionID(ctx context.Context, transactionID string) (*entity.Payment, error) {
	args := m.Called(ctx, transactionID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.Payment), args.Error(1)
}

// GetByInvoiceID mocks the GetByInvoiceID method
func (m *MockIPaymentRepository) GetByInvoiceID(ctx context.Context, invoiceID uuidv7.UUID) ([]*entity.Payment, error) {
	args := m.Called(ctx, invoiceID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Payment), args.Error(1)
}

// GetByUserID mocks the GetByUserID method
func (m *MockIPaymentRepository) GetByUserID(ctx context.Context, userID uuidv7.UUID) ([]*entity.Payment, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Payment), args.Error(1)
}

// List mocks the List method
func (m *MockIPaymentRepository) List(ctx context.Context, status *entity.PaymentStatus, limit, offset int) ([]*entity.Payment, error) {
	args := m.Called(ctx, status, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Payment), args.Error(1)
}

// Count mocks the Count method
func (m *MockIPaymentRepository) Count(ctx context.Context, status *entity.PaymentStatus) (int, error) {
	args := m.Called(ctx, status)
	return args.Int(0), args.Error(1)
}

// Update mocks the Update method
func (m *MockIPaymentRepository) Update(ctx context.Context, payment *entity.Payment) error {
	args := m.Called(ctx, payment)
	return args.Error(0)
}

// Delete mocks the Delete method
func (m *MockIPaymentRepository) Delete(ctx context.Context, id uuidv7.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// NewMockIPaymentRepository creates a new mock instance
func NewMockIPaymentRepository() *MockIPaymentRepository {
	return &MockIPaymentRepository{}
}
