// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/basilex/promenade/internal/modules/billing/domain/entity"
	"github.com/basilex/promenade/pkg/uuidv7"
	"github.com/stretchr/testify/mock"
)

// MockIPlanRepository is a mock of IPlanRepository interface
type MockIPlanRepository struct {
	mock.Mock
}

// Create mocks the Create method
func (m *MockIPlanRepository) Create(ctx context.Context, plan *entity.Plan) error {
	args := m.Called(ctx, plan)
	return args.Error(0)
}

// GetByID mocks the GetByID method
func (m *MockIPlanRepository) GetByID(ctx context.Context, id uuidv7.UUID) (*entity.Plan, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.Plan), args.Error(1)
}

// GetBySlug mocks the GetBySlug method
func (m *MockIPlanRepository) GetBySlug(ctx context.Context, slug string) (*entity.Plan, error) {
	args := m.Called(ctx, slug)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.Plan), args.Error(1)
}

// List mocks the List method
func (m *MockIPlanRepository) List(ctx context.Context, status *entity.PlanStatus, limit, offset int) ([]*entity.Plan, error) {
	args := m.Called(ctx, status, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Plan), args.Error(1)
}

// Count mocks the Count method
func (m *MockIPlanRepository) Count(ctx context.Context, status *entity.PlanStatus) (int, error) {
	args := m.Called(ctx, status)
	return args.Int(0), args.Error(1)
}

// Update mocks the Update method
func (m *MockIPlanRepository) Update(ctx context.Context, plan *entity.Plan) error {
	args := m.Called(ctx, plan)
	return args.Error(0)
}

// Delete mocks the Delete method
func (m *MockIPlanRepository) Delete(ctx context.Context, id uuidv7.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// NewMockIPlanRepository creates a new mock instance
func NewMockIPlanRepository() *MockIPlanRepository {
	return &MockIPlanRepository{}
}
