// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/basilex/promenade/internal/modules/billing/domain/entity"
	"github.com/basilex/promenade/pkg/uuidv7"
	"github.com/stretchr/testify/mock"
)

// MockISubscriptionRepository is a mock of ISubscriptionRepository interface
type MockISubscriptionRepository struct {
	mock.Mock
}

// Create mocks the Create method
func (m *MockISubscriptionRepository) Create(ctx context.Context, subscription *entity.Subscription) error {
	args := m.Called(ctx, subscription)
	return args.Error(0)
}

// GetByID mocks the GetByID method
func (m *MockISubscriptionRepository) GetByID(ctx context.Context, id uuidv7.UUID) (*entity.Subscription, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.Subscription), args.Error(1)
}

// GetByUserID mocks the GetByUserID method
func (m *MockISubscriptionRepository) GetByUserID(ctx context.Context, userID uuidv7.UUID) ([]*entity.Subscription, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Subscription), args.Error(1)
}

// GetActiveByUserID mocks the GetActiveByUserID method
func (m *MockISubscriptionRepository) GetActiveByUserID(ctx context.Context, userID uuidv7.UUID) (*entity.Subscription, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entity.Subscription), args.Error(1)
}

// GetExpiring mocks the GetExpiring method
func (m *MockISubscriptionRepository) GetExpiring(ctx context.Context, days, limit int) ([]*entity.Subscription, error) {
	args := m.Called(ctx, days, limit)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Subscription), args.Error(1)
}

// List mocks the List method
func (m *MockISubscriptionRepository) List(ctx context.Context, status *entity.SubscriptionStatus, limit, offset int) ([]*entity.Subscription, error) {
	args := m.Called(ctx, status, limit, offset)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entity.Subscription), args.Error(1)
}

// Count mocks the Count method
func (m *MockISubscriptionRepository) Count(ctx context.Context, status *entity.SubscriptionStatus) (int, error) {
	args := m.Called(ctx, status)
	return args.Int(0), args.Error(1)
}

// Update mocks the Update method
func (m *MockISubscriptionRepository) Update(ctx context.Context, subscription *entity.Subscription) error {
	args := m.Called(ctx, subscription)
	return args.Error(0)
}

// Delete mocks the Delete method
func (m *MockISubscriptionRepository) Delete(ctx context.Context, id uuidv7.UUID) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// NewMockISubscriptionRepository creates a new mock instance
func NewMockISubscriptionRepository() *MockISubscriptionRepository {
	return &MockISubscriptionRepository{}
}
