// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/modules/audit/domain/entity"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/basilex/promenade/pkg/pagination"

	repository "github.com/basilex/promenade/internal/modules/audit/domain/repository"

	time "time"

	uuid "github.com/google/uuid"
)

// MockIAuditEventRepository is an autogenerated mock type for the IAuditEventRepository type
type MockIAuditEventRepository struct {
	mock.Mock
}

type MockIAuditEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAuditEventRepository) EXPECT() *MockIAuditEventRepository_Expecter {
	return &MockIAuditEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, event
func (_m *MockIAuditEventRepository) Create(ctx context.Context, event *entity.AuditEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAuditEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAuditEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.AuditEvent
func (_e *MockIAuditEventRepository_Expecter) Create(ctx interface{}, event interface{}) *MockIAuditEventRepository_Create_Call {
	return &MockIAuditEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *MockIAuditEventRepository_Create_Call) Run(run func(ctx context.Context, event *entity.AuditEvent)) *MockIAuditEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AuditEvent))
	})
	return _c
}

func (_c *MockIAuditEventRepository_Create_Call) Return(_a0 error) *MockIAuditEventRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAuditEventRepository_Create_Call) RunAndReturn(run func(context.Context, *entity.AuditEvent) error) *MockIAuditEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function with given fields: ctx, before
func (_m *MockIAuditEventRepository) DeleteOlderThan(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuditEventRepository_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type MockIAuditEventRepository_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockIAuditEventRepository_Expecter) DeleteOlderThan(ctx interface{}, before interface{}) *MockIAuditEventRepository_DeleteOlderThan_Call {
	return &MockIAuditEventRepository_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", ctx, before)}
}

func (_c *MockIAuditEventRepository_DeleteOlderThan_Call) Run(run func(ctx context.Context, before time.Time)) *MockIAuditEventRepository_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockIAuditEventRepository_DeleteOlderThan_Call) Return(_a0 int64, _a1 error) *MockIAuditEventRepository_DeleteOlderThan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuditEventRepository_DeleteOlderThan_Call) RunAndReturn(run func(context.Context, time.Time) (int64, error)) *MockIAuditEventRepository_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAction provides a mock function with given fields: ctx, action, params
func (_m *MockIAuditEventRepository) GetByAction(ctx context.Context, action string, params pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error) {
	ret := _m.Called(ctx, action, params)

	if len(ret) == 0 {
		panic("no return value specified for GetByAction")
	}

	var r0 []*entity.AuditEvent
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)); ok {
		return rf(ctx, action, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pagination.Params) []*entity.AuditEvent); ok {
		r0 = rf(ctx, action, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, action, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, pagination.Params) error); ok {
		r2 = rf(ctx, action, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAuditEventRepository_GetByAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAction'
type MockIAuditEventRepository_GetByAction_Call struct {
	*mock.Call
}

// GetByAction is a helper method to define mock.On call
//   - ctx context.Context
//   - action string
//   - params pagination.Params
func (_e *MockIAuditEventRepository_Expecter) GetByAction(ctx interface{}, action interface{}, params interface{}) *MockIAuditEventRepository_GetByAction_Call {
	return &MockIAuditEventRepository_GetByAction_Call{Call: _e.mock.On("GetByAction", ctx, action, params)}
}

func (_c *MockIAuditEventRepository_GetByAction_Call) Run(run func(ctx context.Context, action string, params pagination.Params)) *MockIAuditEventRepository_GetByAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(pagination.Params))
	})
	return _c
}

func (_c *MockIAuditEventRepository_GetByAction_Call) Return(_a0 []*entity.AuditEvent, _a1 *pagination.Metadata, _a2 error) *MockIAuditEventRepository_GetByAction_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAuditEventRepository_GetByAction_Call) RunAndReturn(run func(context.Context, string, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)) *MockIAuditEventRepository_GetByAction_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEntityID provides a mock function with given fields: ctx, entityType, entityID
func (_m *MockIAuditEventRepository) GetByEntityID(ctx context.Context, entityType string, entityID uuid.UUID) ([]*entity.AuditEvent, error) {
	ret := _m.Called(ctx, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetByEntityID")
	}

	var r0 []*entity.AuditEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]*entity.AuditEvent, error)); ok {
		return rf(ctx, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []*entity.AuditEvent); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuditEventRepository_GetByEntityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEntityID'
type MockIAuditEventRepository_GetByEntityID_Call struct {
	*mock.Call
}

// GetByEntityID is a helper method to define mock.On call
//   - ctx context.Context
//   - entityType string
//   - entityID uuid.UUID
func (_e *MockIAuditEventRepository_Expecter) GetByEntityID(ctx interface{}, entityType interface{}, entityID interface{}) *MockIAuditEventRepository_GetByEntityID_Call {
	return &MockIAuditEventRepository_GetByEntityID_Call{Call: _e.mock.On("GetByEntityID", ctx, entityType, entityID)}
}

func (_c *MockIAuditEventRepository_GetByEntityID_Call) Run(run func(ctx context.Context, entityType string, entityID uuid.UUID)) *MockIAuditEventRepository_GetByEntityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockIAuditEventRepository_GetByEntityID_Call) Return(_a0 []*entity.AuditEvent, _a1 error) *MockIAuditEventRepository_GetByEntityID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuditEventRepository_GetByEntityID_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) ([]*entity.AuditEvent, error)) *MockIAuditEventRepository_GetByEntityID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIAuditEventRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.AuditEvent, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.AuditEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.AuditEvent, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.AuditEvent); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuditEventRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIAuditEventRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIAuditEventRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIAuditEventRepository_GetByID_Call {
	return &MockIAuditEventRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIAuditEventRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIAuditEventRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIAuditEventRepository_GetByID_Call) Return(_a0 *entity.AuditEvent, _a1 error) *MockIAuditEventRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuditEventRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*entity.AuditEvent, error)) *MockIAuditEventRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID, params
func (_m *MockIAuditEventRepository) GetByUserID(ctx context.Context, userID uuid.UUID, params pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error) {
	ret := _m.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.AuditEvent
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)); ok {
		return rf(ctx, userID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, pagination.Params) []*entity.AuditEvent); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, userID, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, pagination.Params) error); ok {
		r2 = rf(ctx, userID, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAuditEventRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockIAuditEventRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - params pagination.Params
func (_e *MockIAuditEventRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}, params interface{}) *MockIAuditEventRepository_GetByUserID_Call {
	return &MockIAuditEventRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID, params)}
}

func (_c *MockIAuditEventRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, params pagination.Params)) *MockIAuditEventRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(pagination.Params))
	})
	return _c
}

func (_c *MockIAuditEventRepository_GetByUserID_Call) Return(_a0 []*entity.AuditEvent, _a1 *pagination.Metadata, _a2 error) *MockIAuditEventRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAuditEventRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)) *MockIAuditEventRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filters, params
func (_m *MockIAuditEventRepository) List(ctx context.Context, filters repository.AuditEventFilters, params pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error) {
	ret := _m.Called(ctx, filters, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.AuditEvent
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AuditEventFilters, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)); ok {
		return rf(ctx, filters, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AuditEventFilters, pagination.Params) []*entity.AuditEvent); ok {
		r0 = rf(ctx, filters, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AuditEventFilters, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, filters, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.AuditEventFilters, pagination.Params) error); ok {
		r2 = rf(ctx, filters, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockIAuditEventRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIAuditEventRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filters repository.AuditEventFilters
//   - params pagination.Params
func (_e *MockIAuditEventRepository_Expecter) List(ctx interface{}, filters interface{}, params interface{}) *MockIAuditEventRepository_List_Call {
	return &MockIAuditEventRepository_List_Call{Call: _e.mock.On("List", ctx, filters, params)}
}

func (_c *MockIAuditEventRepository_List_Call) Run(run func(ctx context.Context, filters repository.AuditEventFilters, params pagination.Params)) *MockIAuditEventRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AuditEventFilters), args[2].(pagination.Params))
	})
	return _c
}

func (_c *MockIAuditEventRepository_List_Call) Return(_a0 []*entity.AuditEvent, _a1 *pagination.Metadata, _a2 error) *MockIAuditEventRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockIAuditEventRepository_List_Call) RunAndReturn(run func(context.Context, repository.AuditEventFilters, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)) *MockIAuditEventRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// VerifySignature provides a mock function with given fields: ctx, event, secret
func (_m *MockIAuditEventRepository) VerifySignature(ctx context.Context, event *entity.AuditEvent, secret string) (bool, error) {
	ret := _m.Called(ctx, event, secret)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignature")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditEvent, string) (bool, error)); ok {
		return rf(ctx, event, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditEvent, string) bool); ok {
		r0 = rf(ctx, event, secret)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.AuditEvent, string) error); ok {
		r1 = rf(ctx, event, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIAuditEventRepository_VerifySignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifySignature'
type MockIAuditEventRepository_VerifySignature_Call struct {
	*mock.Call
}

// VerifySignature is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entity.AuditEvent
//   - secret string
func (_e *MockIAuditEventRepository_Expecter) VerifySignature(ctx interface{}, event interface{}, secret interface{}) *MockIAuditEventRepository_VerifySignature_Call {
	return &MockIAuditEventRepository_VerifySignature_Call{Call: _e.mock.On("VerifySignature", ctx, event, secret)}
}

func (_c *MockIAuditEventRepository_VerifySignature_Call) Run(run func(ctx context.Context, event *entity.AuditEvent, secret string)) *MockIAuditEventRepository_VerifySignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.AuditEvent), args[2].(string))
	})
	return _c
}

func (_c *MockIAuditEventRepository_VerifySignature_Call) Return(_a0 bool, _a1 error) *MockIAuditEventRepository_VerifySignature_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIAuditEventRepository_VerifySignature_Call) RunAndReturn(run func(context.Context, *entity.AuditEvent, string) (bool, error)) *MockIAuditEventRepository_VerifySignature_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAuditEventRepository creates a new instance of MockIAuditEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAuditEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAuditEventRepository {
	mock := &MockIAuditEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
