// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/basilex/promenade/internal/modules/audit/domain/entity"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/basilex/promenade/pkg/pagination"

	repository "github.com/basilex/promenade/internal/modules/audit/domain/repository"

	time "time"

	uuid "github.com/google/uuid"
)

// MockAuditEventRepository is an autogenerated mock type for the AuditEventRepository type
type MockAuditEventRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, event
func (_m *MockAuditEventRepository) Create(ctx context.Context, event *entity.AuditEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteOlderThan provides a mock function with given fields: ctx, before
func (_m *MockAuditEventRepository) DeleteOlderThan(ctx context.Context, before time.Time) (int64, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAction provides a mock function with given fields: ctx, action, params
func (_m *MockAuditEventRepository) GetByAction(ctx context.Context, action string, params pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error) {
	ret := _m.Called(ctx, action, params)

	if len(ret) == 0 {
		panic("no return value specified for GetByAction")
	}

	var r0 []*entity.AuditEvent
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)); ok {
		return rf(ctx, action, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pagination.Params) []*entity.AuditEvent); ok {
		r0 = rf(ctx, action, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, action, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, pagination.Params) error); ok {
		r2 = rf(ctx, action, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByEntityID provides a mock function with given fields: ctx, entityType, entityID
func (_m *MockAuditEventRepository) GetByEntityID(ctx context.Context, entityType string, entityID uuid.UUID) ([]*entity.AuditEvent, error) {
	ret := _m.Called(ctx, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetByEntityID")
	}

	var r0 []*entity.AuditEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) ([]*entity.AuditEvent, error)); ok {
		return rf(ctx, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) []*entity.AuditEvent); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockAuditEventRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.AuditEvent, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.AuditEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.AuditEvent, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.AuditEvent); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID, params
func (_m *MockAuditEventRepository) GetByUserID(ctx context.Context, userID uuid.UUID, params pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error) {
	ret := _m.Called(ctx, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.AuditEvent
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)); ok {
		return rf(ctx, userID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, pagination.Params) []*entity.AuditEvent); ok {
		r0 = rf(ctx, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, userID, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, pagination.Params) error); ok {
		r2 = rf(ctx, userID, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// List provides a mock function with given fields: ctx, filters, params
func (_m *MockAuditEventRepository) List(ctx context.Context, filters repository.AuditEventFilters, params pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error) {
	ret := _m.Called(ctx, filters, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.AuditEvent
	var r1 *pagination.Metadata
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AuditEventFilters, pagination.Params) ([]*entity.AuditEvent, *pagination.Metadata, error)); ok {
		return rf(ctx, filters, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AuditEventFilters, pagination.Params) []*entity.AuditEvent); ok {
		r0 = rf(ctx, filters, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.AuditEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AuditEventFilters, pagination.Params) *pagination.Metadata); ok {
		r1 = rf(ctx, filters, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Metadata)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.AuditEventFilters, pagination.Params) error); ok {
		r2 = rf(ctx, filters, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// VerifySignature provides a mock function with given fields: ctx, event, secret
func (_m *MockAuditEventRepository) VerifySignature(ctx context.Context, event *entity.AuditEvent, secret string) (bool, error) {
	ret := _m.Called(ctx, event, secret)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignature")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditEvent, string) (bool, error)); ok {
		return rf(ctx, event, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.AuditEvent, string) bool); ok {
		r0 = rf(ctx, event, secret)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.AuditEvent, string) error); ok {
		r1 = rf(ctx, event, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAuditEventRepository creates a new instance of MockAuditEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditEventRepository {
	mock := &MockAuditEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
