# GitHub Actions workflow for building and deploying Hugo site to GitHub Pages
name: Deploy Website to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "dev"]
    paths:
      - "website/**"
      - "docs/**"
      - ".github/workflows/deploy-website.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write # Required for peaceiris/actions-gh-pages

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.153.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.153.2"
          extended: true

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          cd website
          hugo \
            --gc \
            --minify \
            --baseURL "https://basilex.github.io/promenade/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/dev'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
          force_orphan: true
